// Generated by scripts/build-company-data.mjs from research/raw/*.json — do not edit by hand.
// Compiled 2026-09-28 from public interview reviews and official recruiting pages.
export const COMPANY_DATA: unknown[] = [
 {
  "id": "shinhan-bank",
  "name": "신한은행",
  "shortName": "신한",
  "category": "금융·통신·식품",
  "industry": "은행·금융",
  "talent": [
   "따뜻한 가슴을 지닌 창의적인 열정가",
   "바르게 (신한금융그룹 핵심가치)",
   "빠르게 (신한금융그룹 핵심가치)",
   "다르게 (신한금융그룹 핵심가치)",
   "따뜻한 금융"
  ],
  "process": [
   "서류전형 → SLT 필기시험 → 온라인 역량검사",
   "1차 면접(하루 일정): 찬반 토론면접(약 40분) · 개별 직무/인성면접(약 10분) · 직무 PT",
   "직무 PT: 5개 주제 중 1개 무작위 선택 후 준비, 약 3분 발표 및 상호 질의",
   "2차 임원면접: 인성 중심, 1차에서 부족했던 부분을 검증",
   "채용검진 후 최종 합격"
  ],
  "style": "1차 면접은 연수원에서 토론·직무/인성·PT가 하루 종일 이어지며 특히 토론 비중이 크다고 알려져 있습니다. 2차 임원면접은 인성 위주이나 1차에서 부족했던 부분과 경제·시사를 파고드는 압박성 질문이 나올 수 있습니다.",
  "tips": [
   "토론은 입장보다 납득 가능한 근거와 논리가 핵심이므로 주제를 외우기보다 생각하고 말하는 연습을 하세요.",
   "평소 경제 기사 스크랩과 금융 보고서를 읽어 금리·물가 등 시사 이슈를 은행 관점으로 정리하세요.",
   "PT에서는 다른 지원자 발표에 대한 질문도 평가될 수 있으니 질문거리를 미리 고민해 두세요.",
   "대출 연장·펀드 손실 등 고객 응대 롤플레잉 질문에 대비해 기본 금융상품 지식을 익혀 두세요.",
   "면접이 저녁까지 이어지므로 장시간 집중력을 유지하는 연습이 필요합니다."
  ],
  "questions": [
   {
    "text": "신한은행에 지원한 이유와 왜 금융업인지 말씀해 주세요.",
    "category": "인성",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "여러 은행 중 왜 꼭 신한은행이어야 하는지 설명해 주세요.",
    "category": "기업이해",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "신한이 추구하는 '따뜻한 금융'에 대해 알고 계신가요?",
    "category": "기업이해",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "신한의 핵심가치 '바르게·빠르게·다르게' 중 본인과 가장 맞는 것은 무엇인가요?",
    "category": "기업이해",
    "track": "공통",
    "basis": "공식자료"
   },
   {
    "text": "은행 업무가 힘든데, 이를 이겨낼 수 있는 본인의 강점은 무엇인가요?",
    "category": "인성",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "저희가 본인을 뽑아야 하는 이유를 말씀해 주세요.",
    "category": "인성",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "본인의 직업관은 어떠한지 말씀해 주세요.",
    "category": "인성",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "금융권 입행을 위해 그동안 어떤 노력을 해 오셨나요?",
    "category": "인성",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "학창 시절 가장 좋았던 과목과 가장 어려웠던 과목은 무엇인가요?",
    "category": "경험",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "팀 프로젝트에서 맡았던 역할과 성과를 말씀해 주세요.",
    "category": "경험",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "인턴 경험을 은행 업무에 어떻게 활용할 수 있을까요?",
    "category": "경험",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "매장 근무 중 응대하기 어려웠던 고객과 대처 방법을 말씀해 주세요.",
    "category": "경험",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "투자 손실을 본 고객이 항의한다면 어떻게 대응하시겠습니까?",
    "category": "상황",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "오래 기다린 고객이 신분증을 가져오지 않았다면 어떻게 하시겠습니까?",
    "category": "상황",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "VIP 고객이 자녀 신분증만으로 계좌 개설을 요구하면 어떻게 하시겠습니까?",
    "category": "상황",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "대출 기한 연장을 요청하는 고객을 어떻게 응대하시겠습니까?",
    "category": "상황",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "고객의 자산 포트폴리오를 구성한다면 어떻게 제안하시겠습니까?",
    "category": "직무",
    "track": "일반·영업",
    "basis": "후기"
   },
   {
    "text": "기준금리 인상이 은행에 어떤 영향을 미치는지 설명해 주세요.",
    "category": "직무",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "직접금융과 간접금융의 차이를 설명해 주세요.",
    "category": "직무",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "주택청약 상품을 고객에게 설명하듯 소개해 주세요.",
    "category": "직무",
    "track": "일반·영업",
    "basis": "후기"
   },
   {
    "text": "재건축 초과이익 환수제에 대해 찬반 입장을 정해 토론해 주세요.",
    "category": "PT·토론",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "이중가격제에 대한 찬반 의견을 근거와 함께 말씀해 주세요.",
    "category": "PT·토론",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "장바구니 물가 상승 상황에서 은행이 할 수 있는 방안을 발표해 주세요.",
    "category": "PT·토론",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "미 연준의 급격한 금리 인상기에 WM 고객 관리 전략을 제시해 주세요.",
    "category": "PT·토론",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "스택과 큐의 차이를 설명해 주세요.",
    "category": "기술",
    "track": "디지털·IT",
    "basis": "후기"
   }
  ],
  "sources": [
   {
    "title": "링커리어 - 2025 신한은행 채용 대비 합격 후기.zip",
    "url": "https://community.linkareer.com/employment_data/4109056"
   },
   {
    "title": "링커리어 - [신한은행] 2024 상반기 신입 1차 면접 합격후기",
    "url": "https://community.linkareer.com/interview/3365469"
   },
   {
    "title": "링커리어 - [신한은행] 2025 상반기 신입행원 서류/면접 후기",
    "url": "https://community.linkareer.com/interview/4847202"
   },
   {
    "title": "잡코리아 - 신한은행 실제 면접 질문",
    "url": "https://www.jobkorea.co.kr/starter/review/view?c_idx=3&ctgr_code=5"
   },
   {
    "title": "뉴스투데이 - 5대 시중은행 서로 다른 인재상",
    "url": "https://www.news2day.co.kr/article/20220825500159"
   },
   {
    "title": "신한금융그룹 - 미션·핵심가치",
    "url": "https://www.shinhangroup.com/kr/about/group/mission"
   },
   {
    "title": "이투데이 - 신한은행, 평범한 사람들이 만드는 비범한 조직",
    "url": "https://www.etoday.co.kr/news/view/771297"
   }
  ]
 },
 {
  "id": "kb-bank",
  "name": "KB국민은행",
  "shortName": "국민은행",
  "category": "금융·통신·식품",
  "industry": "은행·금융",
  "talent": [
   "창의적인 사고와 행동으로 변화를 선도하며 고객가치를 향상시키는 프로금융인",
   "고객우선주의",
   "자율과 책임",
   "적극적 사고와 행동",
   "다양한 가치의 존중"
  ],
  "process": [
   "서류전형 → 필기전형",
   "1차 면접(2025 상반기 1박 2일 합숙): 세일즈면접 · BEI면접 · 찬반 토론면접 · 팀빌딩",
   "1차 면접 중 인성검사·TOPCIT(디지털 역량) 응시",
   "2차 임원면접: 다대다 인성면접(약 45분, 외부 면접관 포함)"
  ],
  "style": "1차는 연수원 합숙 형식으로 고객 역할 면접관에게 상품을 추천하는 세일즈면접, 자소서 기반 BEI, 찬반 토론, 팀빌딩 게임까지 다양하게 평가합니다. 2차 임원면접은 인성 위주 다대다로 진행되며 입행 의지와 가치관을 확인합니다.",
  "tips": [
   "세일즈면접은 고객 정보(연령·자산·여유자금)를 보고 상품을 추천하므로 예금·펀드·대출 상환 방식 등 기본 상품 지식을 익혀 두세요.",
   "BEI는 자소서 기반 인성 질문이 많으니 경험마다 동기와 배운 점을 정리하세요.",
   "합숙 중 팀빌딩·레크리에이션 참여 태도도 평가될 수 있어 협업과 적극성을 보여 주는 것이 좋습니다.",
   "꾸준히 경제신문을 읽고 KB 앱·빅테크 경쟁 등 은행 이슈에 대한 본인 의견을 준비하세요.",
   "임원면접에서는 경험을 과장하지 말고 솔직하고 일관되게 답하는 것이 중요하다는 후기가 많습니다."
  ],
  "questions": [
   {
    "text": "KB국민은행에 지원한 동기와 이를 위해 준비한 것을 말씀해 주세요.",
    "category": "인성",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "KB국민은행에 대해 어떤 이미지를 가지고 계신가요?",
    "category": "기업이해",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "은행원에게 가장 중요한 것을 한 단어로 표현해 주세요.",
    "category": "인성",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "국민은행 인재상 중 본인과 가장 부합하는 것은 무엇인가요?",
    "category": "기업이해",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "위임받은 권한 안에서 스스로 판단하고 결과까지 책임진 경험이 있나요?",
    "category": "경험",
    "track": "공통",
    "basis": "공식자료"
   },
   {
    "text": "공공선을 위해 일했던 경험이 있으신가요?",
    "category": "경험",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "최근 감명 깊게 읽은 책은 무엇인가요?",
    "category": "인성",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "최근 주변 사람에게 들은 본인의 단점은 무엇인가요?",
    "category": "인성",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "조직에서 갈등을 해결한 사례를 말씀해 주세요.",
    "category": "경험",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "여러 업무를 동시에 처리해야 할 때 본인만의 방법이 있나요?",
    "category": "경험",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "은행 업무 공부로 쌓이는 스트레스는 어떻게 해소하시나요?",
    "category": "인성",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "완성도가 부족해도 기한 내 제출과 늦더라도 완성 중 무엇을 택하시겠습니까?",
    "category": "상황",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "원하지 않는 업무를 배정받는다면 어떻게 하시겠습니까?",
    "category": "상황",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "고객이 경쟁 은행이 더 좋다고 한다면 어떻게 대응하시겠습니까?",
    "category": "상황",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "업무 지식과 영업 실적 중 무엇을 우선하시겠습니까?",
    "category": "인성",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "국민은행의 약점은 무엇이고 경영진이라면 어떻게 극복하시겠습니까?",
    "category": "기업이해",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "KB 모바일 앱의 문제점과 개선 방안을 말씀해 주세요.",
    "category": "기업이해",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "빅테크와의 경쟁에서 KB가 취해야 할 전략은 무엇이라고 보시나요?",
    "category": "기업이해",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "펀드 수익률이 불규칙한 이유를 고객에게 설명해 주세요.",
    "category": "직무",
    "track": "일반·영업",
    "basis": "후기"
   },
   {
    "text": "예금을 모두 MMF로 바꾸고 싶다는 고객에게 어떻게 조언하시겠습니까?",
    "category": "직무",
    "track": "일반·영업",
    "basis": "후기"
   },
   {
    "text": "원금균등·원리금균등·만기일시 상환 방식의 차이를 설명해 주세요.",
    "category": "직무",
    "track": "일반·영업",
    "basis": "후기"
   },
   {
    "text": "데이터 3법 개정의 주요 내용을 설명해 주세요.",
    "category": "직무",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "저신용자 신용대출 공급 축소에 대해 찬반 입장을 정해 토론해 주세요.",
    "category": "PT·토론",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "자율주행차 도입에 대해 찬반 입장을 나눠 토론해 주세요.",
    "category": "PT·토론",
    "track": "공통",
    "basis": "후기"
   }
  ],
  "sources": [
   {
    "title": "링커리어 - [국민은행] 2025 상반기 신입 1차 면접 후기",
    "url": "https://community.linkareer.com/interview/4451167"
   },
   {
    "title": "링커리어 - [국민은행] 2024 하반기 UB부문 신입 2차 면접 후기",
    "url": "https://community.linkareer.com/interview/4193852"
   },
   {
    "title": "링커리어 - [KB국민은행] UB 신입행원 1차/최종면접 합격후기",
    "url": "https://community.linkareer.com/intern_activity/832267"
   },
   {
    "title": "자소설닷컴 - KB국민은행 합격 후기: 자소서 팁, 인적성, 면접 질문",
    "url": "https://jasoseol.com/blog/post/kb%EA%B5%AD%EB%AF%BC%EC%9D%80%ED%96%89-%ED%95%A9%EA%B2%A9-%ED%9B%84%EA%B8%B0-%EC%9E%90%EC%86%8C%EC%84%9C-%ED%8C%81-%EC%9D%B8%EC%A0%81%EC%84%B1-%EB%A9%B4%EC%A0%91-%EC%A7%88%EB%AC%B8%EA%B9%8C/"
   },
   {
    "title": "잡코리아 - 국민은행 실제 면접 질문",
    "url": "https://www.jobkorea.co.kr/starter/review/view?C_Idx=9&Ctgr_Code=5"
   },
   {
    "title": "KB국민은행 - 인재상",
    "url": "https://omoney.kbstar.com/quics?page=C017618"
   }
  ]
 },
 {
  "id": "hana-bank",
  "name": "하나은행",
  "shortName": "하나",
  "category": "금융·통신·식품",
  "industry": "은행·금융",
  "talent": [
   "온기·용기·동기의 마음을 실천하는 하나인",
   "사람에 대한 온기 (Humanity)",
   "미래에 대한 용기 (First Mover)",
   "성장에 대한 동기 (Growth Mind)",
   "Integrity(정직·신뢰)"
  ],
  "process": [
   "서류전형 → 필기전형(NCS·인성), 디지털·ICT는 코딩테스트",
   "1차 면접(하루 3종): BEI 다대다 역량면접 · 세일즈 PT면접 · 하나 FIT 1:1 면접",
   "세일즈 PT: 약 30분 준비, 7분 발표 + 8분 질의응답",
   "최종 임원면접: 다대다 인성·시사 면접"
  ],
  "style": "1차는 하나글로벌캠퍼스에서 하루 동안 BEI·세일즈 PT·하나 FIT 세 가지 면접을 치르며, 하나 FIT는 인성검사 결과를 바탕으로 한 1:1 대화형으로 비교적 편안합니다. 최종 임원면접은 다대다로 금융 시사, 손님 응대, 조직 적응 질문이 섞여 나옵니다.",
  "tips": [
   "'고객' 대신 '손님'이라는 하나은행의 용어를 익혀 두면 좋다는 후기가 있습니다.",
   "다른 은행이 아닌 하나은행이어야 하는 이유를 본인 경험과 연결해 명확히 준비하세요.",
   "세일즈 PT는 전사 전략이 아니라 지점 단위로, 구체적인 손님군을 정해 상품 판매 전략을 짜는 연습을 하세요.",
   "환율·기준금리 등 최신 수치와 그 의미를 말할 수 있도록 정리하세요.",
   "하나원큐 등 자사 앱과 서비스를 직접 써 보고 장단점을 준비하세요."
  ],
  "questions": [
   {
    "text": "1분 자기소개와 함께 지원 동기를 말씀해 주세요.",
    "category": "인성",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "다른 은행이 아닌 하나은행이어야 하는 이유는 무엇인가요?",
    "category": "기업이해",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "본인이 생각하는 이상적인 은행원은 어떤 모습인가요?",
    "category": "인성",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "'고객'과 '손님'이라는 표현은 어떤 차이가 있다고 보시나요?",
    "category": "기업이해",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "온기·용기·동기 중 본인을 가장 잘 나타내는 것은 무엇인가요?",
    "category": "인성",
    "track": "공통",
    "basis": "공식자료"
   },
   {
    "text": "하나원큐 앱의 장점과 단점을 하나씩 말씀해 주세요.",
    "category": "기업이해",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "최근 은행업의 트렌드는 무엇이라고 보시나요?",
    "category": "기업이해",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "MZ세대 손님을 사로잡을 하나은행만의 차별화 전략은 무엇일까요?",
    "category": "기업이해",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "본인이 사는 지역에서 하나은행의 입지를 어떻게 평가하시나요?",
    "category": "기업이해",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "현재 환율과 기준금리 수준을 알고 계신가요?",
    "category": "직무",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "최근 원화 강세의 원인은 무엇이라고 보시나요?",
    "category": "직무",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "본인은 자산을 어떻게 관리하고 계신가요?",
    "category": "직무",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "손님이 상품 권유를 거절하면 어떻게 대응하시겠습니까?",
    "category": "상황",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "민원을 제기하는 손님을 어떻게 응대하시겠습니까?",
    "category": "상황",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "상사의 부당한 지시를 받는다면 어떻게 하시겠습니까?",
    "category": "상황",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "도움이 필요한 동료가 있을 때 어떻게 지원하시겠습니까?",
    "category": "상황",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "희망하지 않은 직무로 배치된다면 어떻게 하시겠습니까?",
    "category": "상황",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "지금까지 가장 열중했던 경험은 무엇인가요?",
    "category": "경험",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "다른 사람에게 도움을 주거나 받았던 경험을 말씀해 주세요.",
    "category": "경험",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "중요한 의사결정을 내렸던 경험과 그 과정을 말씀해 주세요.",
    "category": "경험",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "본인의 단점은 무엇인가요?",
    "category": "인성",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "처음 만난 사람과 친해지는 본인만의 방법이 있나요?",
    "category": "인성",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "제시된 영업점 상황에서 상품 2개를 골라 판매 전략을 발표해 주세요.",
    "category": "PT·토론",
    "track": "일반·영업",
    "basis": "후기"
   },
   {
    "text": "고소득층 지역 PB센터라면 어떤 손님에게 어떤 상품을 제안하시겠습니까?",
    "category": "PT·토론",
    "track": "일반·영업",
    "basis": "후기"
   },
   {
    "text": "실시간 데이터 스트리밍 기술을 은행에 어떻게 적용할 수 있을까요?",
    "category": "기술",
    "track": "디지털·IT",
    "basis": "후기"
   }
  ],
  "sources": [
   {
    "title": "링커리어 - 2025 하나은행 하반기 신입 채용 대비 합격 후기",
    "url": "https://community.linkareer.com/employment_data/4802687"
   },
   {
    "title": "링커리어 - [하나은행] 2025 상반기 신입 최종합격 후기",
    "url": "https://community.linkareer.com/final_review/4451930"
   },
   {
    "title": "velog - 2025년 하나은행 상반기 최종합격 후기 (디지털/ICT)",
    "url": "https://velog.io/@devwoong/2025%EB%85%84-%ED%95%98%EB%82%98%EC%9D%80%ED%96%89-%EC%83%81%EB%B0%98%EA%B8%B0-%EC%B5%9C%EC%A2%85%ED%95%A9%EA%B2%A9-%ED%9B%84%EA%B8%B0-%EB%94%94%EC%A7%80%ED%84%B8ICT"
   },
   {
    "title": "링커리어 - 2025 하나은행 체험형 인턴 채용 대비 합격 후기 모음",
    "url": "https://community.linkareer.com/employment_data/4443436"
   },
   {
    "title": "뉴스투데이 - 5대 시중은행 서로 다른 인재상",
    "url": "https://www.news2day.co.kr/article/20220825500159"
   }
  ]
 },
 {
  "id": "nh-bank",
  "name": "NH농협은행",
  "shortName": "농협은행",
  "category": "금융·통신·식품",
  "industry": "은행·금융",
  "talent": [
   "최고의 금융전문가",
   "소통하고 협력하는 사람",
   "사회적 책임을 실천하는 사람",
   "변화를 선도하는 사람",
   "고객을 먼저 생각하는 사람"
  ],
  "process": [
   "서류전형(자기소개서 + 온라인 인·적성평가 Lv.1)",
   "필기전형: 인·적성평가 Lv.2 · 직무능력평가 · 직무상식평가 등",
   "면접전형: 집단면접 · 토의(토론)면접 · RP · PT · 심층면접 중 채용별로 구성",
   "6급 사례: 원데이 면접으로 집단면접(다대다) + PT면접(1:1) 진행",
   "채용신체검사 후 최종 합격"
  ],
  "style": "집단면접은 공통 질문이 많고 꼬리질문 포함 8~10개 정도로 대체로 편안하며 면접관이 잘 들어 주는 편이라는 후기가 많습니다. PT는 짧은 준비 후 발표하며 질의응답은 비교적 날카롭고, 토의면접은 적극적인 토론을 요구받기도 합니다.",
  "tips": [
   "'왜 꼭 농협은행인가'에 대한 진솔한 답변이 합격의 핵심이라는 후기가 많습니다.",
   "농업·농촌, 농협의 공익적 가치와 ESG 등 농협은행만의 특수성을 이해하고 답변에 녹이세요.",
   "소통 능력과 팀워크를 강조하고, 경험 답변은 두괄식으로 40초 안팎으로 조절하세요.",
   "PT는 상품 특징·타깃 고객·판매 활성화 방안 구조로 짧은 시간 안에 정리하는 연습을 하세요.",
   "금융·IT 트렌드와 금리 등 시사 이슈를 키워드 중심으로 정리해 두세요."
  ],
  "questions": [
   {
    "text": "농협은행에 꼭 입행해야 하는 이유는 무엇인가요?",
    "category": "인성",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "타행과 다른 농협은행의 특수성을 고려할 때 어떤 행원이 되고 싶으신가요?",
    "category": "기업이해",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "농협은행의 강점은 무엇이라고 생각하시나요?",
    "category": "기업이해",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "알고 있는 농협은행 서비스를 하나 설명해 주세요.",
    "category": "기업이해",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "농협은행의 ESG 경영에 대해 알고 계신가요?",
    "category": "기업이해",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "농협의 공익적 가치는 무엇이라고 생각하시나요?",
    "category": "기업이해",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "입행 후 농업과 농협에 어떻게 기여하실 수 있나요?",
    "category": "기업이해",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "최근 국제 금융 이슈 하나와 그것이 농협은행에 미칠 영향을 말씀해 주세요.",
    "category": "직무",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "최근 수신금리 관련 이슈에 대해 의견을 말씀해 주세요.",
    "category": "직무",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "불완전판매를 막기 위해 직원으로서 어떻게 하시겠습니까?",
    "category": "직무",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "사업 계획을 세울 때 가장 중요한 요소는 무엇이라고 보시나요?",
    "category": "직무",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "자연재해가 발생하면 농협은 어떤 역할을 해야 할까요?",
    "category": "상황",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "원하는 직무에 배치되지 않으면 어떻게 하시겠습니까?",
    "category": "상황",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "악성 민원 고객과는 어떻게 소통하시겠습니까?",
    "category": "상황",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "조직에서 목표를 달성했던 성공 경험을 말씀해 주세요.",
    "category": "경험",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "조직 내 갈등으로 실패했던 경험과 배운 점을 말씀해 주세요.",
    "category": "경험",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "다른 사람과 협업해 시너지를 냈던 경험이 있나요?",
    "category": "경험",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "설득으로 다른 사람의 마음을 움직인 경험을 말씀해 주세요.",
    "category": "경험",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "다른 사람을 도왔던 경험을 말씀해 주세요.",
    "category": "경험",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "고객과의 약속을 끝까지 책임졌던 경험이 있나요?",
    "category": "경험",
    "track": "공통",
    "basis": "공식자료"
   },
   {
    "text": "세대 갈등을 해결할 방안은 무엇이라고 생각하시나요?",
    "category": "인성",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "일을 할 때 가장 중요하게 생각하는 가치는 무엇인가요?",
    "category": "인성",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "걷기 연동 우대금리 적금의 타깃 고객과 판매 활성화 방안을 발표해 주세요.",
    "category": "PT·토론",
    "track": "일반·영업",
    "basis": "후기"
   },
   {
    "text": "비대면 진료 법제화에 대해 찬반 입장을 정해 토론해 주세요.",
    "category": "PT·토론",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "농협은행 유튜브 구독자 100만을 달성할 방안을 논의해 주세요.",
    "category": "PT·토론",
    "track": "공통",
    "basis": "후기"
   }
  ],
  "sources": [
   {
    "title": "NH농협은행 - 채용절차",
    "url": "https://www.nhbank.com/goSubPage.do?srchGb=KO_NHJB_08"
   },
   {
    "title": "NH농협은행 - 인재상",
    "url": "https://www.nhbank.com/goSubPage.do?srchGb=KO_NHJB_02"
   },
   {
    "title": "링커리어 - [NH농협은행] 2023 상반기 신입 6급 면접 후기",
    "url": "https://community.linkareer.com/interview/3439541"
   },
   {
    "title": "링커리어 - [농협은행] 2023 상반기 6급 서류/필기/면접 후기",
    "url": "https://community.linkareer.com/interview/2806765"
   },
   {
    "title": "링커리어 - [NH농협은행] 2024 하반기 신입 면접 후기",
    "url": "https://community.linkareer.com/interview/3658830"
   },
   {
    "title": "탑뱅커 - 농협은행 2023 하반기 5급 면접후기",
    "url": "https://topbanker.co.kr/page.php?step=view&menuSeq=185&seq=249&returnPath=L3BhZ2UucGhwP3N0ZXA9bGlzdCZtZW51U2VxPTE4NQ%3D%3D"
   },
   {
    "title": "잡코리아 - NH농협은행 실제 면접 질문",
    "url": "https://www.jobkorea.co.kr/starter/review/view?c_idx=5056&ctgr_code=5"
   },
   {
    "title": "자소설닷컴 - NH농협은행 합격 후기: 자소서 팁, 인적성, 면접질문",
    "url": "https://jasoseol.com/blog/post/nh%EB%86%8D%ED%98%91%EC%9D%80%ED%96%89-%ED%95%A9%EA%B2%A9-%ED%9B%84%EA%B8%B0-%EC%9E%90%EC%86%8C%EC%84%9C-%ED%8C%81-%EC%9D%B8%EC%A0%81%EC%84%B1-%EB%A9%B4%EC%A0%91%EC%A7%88%EB%AC%B8/"
   }
  ]
 },
 {
  "id": "kt",
  "name": "KT",
  "shortName": "KT",
  "category": "금융·통신·식품",
  "industry": "통신·ICT",
  "talent": [
   "고객 (고객가치)",
   "역량 (본질적 역량)",
   "실질 (실질적 성과)",
   "화합 (상호 존중의 화합)",
   "고객의 보다 나은 미래를 만드는 디지털 혁신 파트너",
   "AICT 컴퍼니 (통신+IT+AI)"
  ],
  "process": [
   "서류전형(자기소개서) → 인적성검사, SW개발 직무는 코딩테스트",
   "1차 실무면접: 사전 제출 PT 과제 발표(약 10분) + 질의응답, 자소서·전공 검증",
   "2차 임원면접: 경험·인성 중심, 회사 비전과 인재상 부합도 확인"
  ],
  "style": "1차 실무면접은 면접관 3명과 지원자 1명이 가까운 거리에서 마주 앉아 PT 발표 후 자소서와 전공 지식을 묻는 방식이며 압박 강도는 중간 정도라는 후기가 많습니다. 경험의 의도, 어려움 극복 과정, 성과를 원하는 답이 나올 때까지 집요하게 확인하는 편입니다.",
  "tips": [
   "자소서 기반 예상 질문을 수십 개 만들고 녹음하며 답변을 체화하세요.",
   "경험마다 '왜 했는지–어떻게 극복했는지–무엇을 얻었는지'를 구체적인 수치와 함께 정리하세요.",
   "지원 직무의 통신·네트워크 등 전공 기초 지식을 다시 점검하세요.",
   "PT 자료는 간결하게 만들고 발표 스크립트로 보완하며, 발표 내용 질의응답에 대비하세요.",
   "AICT 전환, B2B 사업 등 KT의 사업 방향을 파악하고 입사 의지를 분명히 표현하세요."
  ],
  "questions": [
   {
    "text": "왜 KT에 지원하셨나요?",
    "category": "인성",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "KT의 기회와 위기는 각각 무엇이라고 보시나요?",
    "category": "기업이해",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "경쟁사와 비교했을 때 KT의 강점은 무엇인가요?",
    "category": "기업이해",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "KT가 앞으로 나아가야 할 방향성에 대해 말씀해 주세요.",
    "category": "기업이해",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "KT의 B2B 상품 하나를 골라 장단점을 설명해 주세요.",
    "category": "기업이해",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "KT의 AICT 컴퍼니 전환에서 본인이 기여할 수 있는 부분은 무엇인가요?",
    "category": "기업이해",
    "track": "공통",
    "basis": "공식자료"
   },
   {
    "text": "KT의 핵심가치 중 본인과 가장 부합하는 것은 무엇인가요?",
    "category": "인성",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "지원 직무에서 본인의 가장 뛰어난 역량은 무엇인가요?",
    "category": "직무",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "입사 후 본인의 하루 일과를 그려 본다면 어떨까요?",
    "category": "직무",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "좋은 아이디어가 있다면 조직에 어떻게 제안하시겠습니까?",
    "category": "직무",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "전공과 다른 직무에 지원한 이유는 무엇인가요?",
    "category": "인성",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "팀 활동 중 갈등이 생겼을 때 어떻게 해결하셨나요?",
    "category": "경험",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "가장 열정적으로 임했던 경험을 말씀해 주세요.",
    "category": "경험",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "그 경험을 하게 된 의도와 어려움을 극복한 과정, 성과를 말씀해 주세요.",
    "category": "경험",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "조직 관점에서 어려웠던 경험과 해결 과정을 말씀해 주세요.",
    "category": "경험",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "신입사원이 1년 안에 퇴사하는 이유는 무엇이라고 생각하시나요?",
    "category": "인성",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "주말 출근이 필요하다면 가능하신가요?",
    "category": "상황",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "사전 제출한 PT 과제를 10분간 발표하고 질문에 답해 주세요.",
    "category": "PT·토론",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "OSPF 라우팅 프로토콜의 동작 방식을 설명해 주세요.",
    "category": "기술",
    "track": "네트워크·인프라",
    "basis": "후기"
   },
   {
    "text": "NAT64가 무엇이고 어떤 상황에서 쓰이는지 설명해 주세요.",
    "category": "기술",
    "track": "네트워크·인프라",
    "basis": "후기"
   },
   {
    "text": "네트워크 텔레메트리는 어떤 용도로 사용되나요?",
    "category": "기술",
    "track": "연구개발",
    "basis": "후기"
   },
   {
    "text": "SDN 관련 연구 경험을 좀 더 깊이 설명해 주세요.",
    "category": "기술",
    "track": "연구개발",
    "basis": "후기"
   },
   {
    "text": "접지에 대해 아는 대로 설명해 주세요.",
    "category": "기술",
    "track": "에너지·설비",
    "basis": "후기"
   },
   {
    "text": "수배전 설비에 쓰이는 차단기 종류를 말씀해 주세요.",
    "category": "기술",
    "track": "에너지·설비",
    "basis": "후기"
   }
  ],
  "sources": [
   {
    "title": "링커리어 - 2025 KT 채용 합격 자료 모음집",
    "url": "https://community.linkareer.com/employment_data/4103707"
   },
   {
    "title": "링커리어 - [KT] 23년 하반기 신입 채용 면접합격 후기",
    "url": "https://community.linkareer.com/interview/3093039"
   },
   {
    "title": "링커리어 - [KT] 23년 하반기 직무 면접 합격 후기",
    "url": "https://community.linkareer.com/interview/3121122"
   },
   {
    "title": "잡코리아 - KT 실제 면접 질문",
    "url": "https://www.jobkorea.co.kr/Starter/review/view?C_Idx=23&Ctgr_Code=5"
   },
   {
    "title": "자소설닷컴 - KT 합격 후기: 자소서 팁, 인적성, 면접 질문",
    "url": "https://jasoseol.com/blog/post/kt-%ED%95%A9%EA%B2%A9-%ED%9B%84%EA%B8%B0-%EC%9E%90%EC%86%8C%EC%84%9C-%ED%8C%81-%EC%9D%B8%EC%A0%81%EC%84%B1-%EB%A9%B4%EC%A0%91-%EC%A7%88%EB%AC%B8%EA%B9%8C%EC%A7%80/"
   },
   {
    "title": "KT Enterprise - 김영섭 대표 취임, 고객가치·본질적 역량·실질적 성과·상호 존중의 화합",
    "url": "https://enterprise.kt.com/bt/mediareport/2175.do"
   },
   {
    "title": "서울신문 - AICT 컴퍼니로 탈바꿈 나선 KT, 조직개편 단행",
    "url": "https://www.seoul.co.kr/news/economy/industry/2024/11/29/20241129500110"
   }
  ]
 },
 {
  "id": "cj-cheiljedang",
  "name": "CJ제일제당",
  "shortName": "CJ제일제당",
  "category": "금융·통신·식품",
  "industry": "식품·바이오",
  "talent": [
   "역량 있는 반듯한 하고잡이",
   "ONLYONE 정신 (최초·최고·차별화)",
   "정직",
   "열정",
   "창의",
   "존중",
   "글로벌 인재"
  ],
  "process": [
   "지원서 접수 → AI역량검사 → 서류전형 → TEST전형(CAT·CFT, 시기별 변동)",
   "1차 면접: 직무 전문성 면접 + 직무별 토론·PT면접, CJ Chat(AI역량검사 기반) 면접",
   "2차 면접: 임원 개별 심화 면접(자소서 검증·가치관·입사 후 포부)",
   "건강검진 후 최종 합격"
  ],
  "style": "비즈니스 캐주얼 복장으로 진행되며 딱딱하지 않고 압박이 거의 없는 편안한 분위기라는 후기가 많습니다. 자소서 경험에 대한 꼬리질문과 CJ 제품·산업 이해를 묻는 질문이 중심이고, 토론면접은 주장을 관철하기보다 소통하는 과정을 봅니다.",
  "tips": [
   "CJ 제품을 직접 써 보고 가장 좋아하는 제품과 개선점을 구체적으로 준비하세요.",
   "영업 직무라면 마트를 여러 곳 돌며 프로모션과 진열 방식을 직접 살펴보는 것이 도움이 됐다는 후기가 있습니다.",
   "토론면접에서는 공격적인 태도보다 상대 의견을 존중하며 합의를 이끄는 모습이 중요합니다.",
   "식품 트렌드와 산업 뉴스를 꾸준히 보고, 자소서에 쓴 활동을 다시 정리하세요.",
   "PT가 있는 직무는 자소서 기획안을 발표하므로 대본 없이 자연스럽게 설명하는 연습을 하세요."
  ],
  "questions": [
   {
    "text": "자기소개와 함께 CJ제일제당 지원 동기를 말씀해 주세요.",
    "category": "인성",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "식품업에 대해 어떤 생각을 가지고 계신가요?",
    "category": "기업이해",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "CJ제일제당 제품 중 가장 좋아하는 것과 개선할 점은 무엇인가요?",
    "category": "기업이해",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "경쟁사와 비교한 CJ제일제당의 차별점은 무엇이라고 보시나요?",
    "category": "기업이해",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "현재 식품 트렌드와 앞으로의 전망을 말씀해 주세요.",
    "category": "직무",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "'하고잡이'처럼 스스로 일을 만들어 성과를 낸 경험이 있나요?",
    "category": "경험",
    "track": "공통",
    "basis": "공식자료"
   },
   {
    "text": "푸드 세일즈 직무는 어떤 일이라고 생각하시나요?",
    "category": "직무",
    "track": "영업",
    "basis": "후기"
   },
   {
    "text": "명절 선물세트에 햇반이 잘 포함되지 않는 이유는 무엇일까요?",
    "category": "직무",
    "track": "영업",
    "basis": "후기"
   },
   {
    "text": "구매 담당자로서 원가 절감을 위한 경영 지식을 갖추고 계신가요?",
    "category": "직무",
    "track": "구매",
    "basis": "후기"
   },
   {
    "text": "CJ의 품질경영시스템(CJQMS)에 대해 알고 계신가요?",
    "category": "직무",
    "track": "품질",
    "basis": "후기"
   },
   {
    "text": "본인이 개발한 제품과 시중 제품의 차별점은 무엇인가요?",
    "category": "직무",
    "track": "연구개발",
    "basis": "후기"
   },
   {
    "text": "실험실에서 어떤 활동을 하셨는지 말씀해 주세요.",
    "category": "경험",
    "track": "연구개발",
    "basis": "후기"
   },
   {
    "text": "가장 열정적으로 했던 일과 그중 힘들었던 점을 말씀해 주세요.",
    "category": "경험",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "실패 경험과 이를 극복한 과정을 말씀해 주세요.",
    "category": "경험",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "팀 내 갈등을 해결한 경험이 있나요?",
    "category": "경험",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "조직에서 맡고 싶은 역할과 맡기 싫은 역할은 무엇인가요?",
    "category": "인성",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "본인의 강점과 약점을 말씀해 주세요.",
    "category": "인성",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "스트레스는 어떻게 해소하시나요?",
    "category": "인성",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "본인이 생각하는 워라밸이란 무엇인가요?",
    "category": "인성",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "이상적인 목표와 현실적인 목표 중 무엇을 택하시겠습니까?",
    "category": "인성",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "입사 5년 후 본인의 목표는 무엇인가요?",
    "category": "인성",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "일이 예상대로 진행되지 않으면 어떻게 하시겠습니까?",
    "category": "상황",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "나이 어린 선배와 일하게 되면 어떤 마음가짐을 가지시겠습니까?",
    "category": "상황",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "지원 직무가 아닌 다른 파트로 배치되어도 괜찮으신가요?",
    "category": "상황",
    "track": "공통",
    "basis": "후기"
   },
   {
    "text": "자기소개서에 작성한 기획안을 PT로 발표해 주세요.",
    "category": "PT·토론",
    "track": "공통",
    "basis": "후기"
   }
  ],
  "sources": [
   {
    "title": "링커리어 - 2025 CJ그룹 면접 질문 모음집",
    "url": "https://community.linkareer.com/employment_data/4227939"
   },
   {
    "title": "링커리어 - 2025 하반기 CJ그룹 합격자료",
    "url": "https://community.linkareer.com/employment_data/4746576"
   },
   {
    "title": "링커리어 - [CJ제일제당] 2023 상반기 B2B 마케팅 서류/AI역검/면접 후기",
    "url": "https://community.linkareer.com/interview/2799158"
   },
   {
    "title": "링커리어 - [CJ제일제당] 2023 상반기 신입 서류/면접 후기",
    "url": "https://community.linkareer.com/interview/2845543"
   },
   {
    "title": "링커리어 - [CJ제일제당] 2024 하반기 ESG 기획 신입 면접 후기",
    "url": "https://community.linkareer.com/interview/4164024"
   },
   {
    "title": "잡코리아 - CJ제일제당 실제 면접 질문",
    "url": "https://www.jobkorea.co.kr/starter/review/view?c_idx=82&ctgr_code=5"
   },
   {
    "title": "사람인 - CJ제일제당 면접 후기",
    "url": "https://www.saramin.co.kr/zf_user/interview-review?company_nm=CJ%EC%A0%9C%EC%9D%BC%EC%A0%9C%EB%8B%B9"
   },
   {
    "title": "CJ 뉴스룸 - CJ제일제당 채용 담당자가 알려주는 2023 채용 합격 꿀팁",
    "url": "https://cjnews.cj.net/cj%EC%A0%9C%EC%9D%BC%EC%A0%9C%EB%8B%B9-%EC%B1%84%EC%9A%A9-%EB%8B%B4%EB%8B%B9%EC%9E%90%EA%B0%80-%EC%95%8C%EB%A0%A4%EC%A3%BC%EB%8A%94-2023-%EC%B1%84%EC%9A%A9-%ED%95%A9%EA%B2%A9-%EA%BF%80%ED%8C%81/"
   },
   {
    "title": "CJ 뉴스룸 - CJ그룹, 2025년 상반기 신입사원 채용 시작",
    "url": "https://cjnews.cj.net/cj%EA%B7%B8%EB%A3%B9-2025%EB%85%84-%EC%83%81%EB%B0%98%EA%B8%B0-%EC%8B%A0%EC%9E%85%EC%82%AC%EC%9B%90-%EC%B1%84%EC%9A%A9-%EC%8B%9C%EC%9E%91/"
   },
   {
    "title": "링커리어 - 2025 CJ 인재상 '하고잡이'란?",
    "url": "https://community.linkareer.com/employment_data/4133809"
   }
  ]
 }
];
