// Generated by scripts/build-role-data.ts from research/role-raw — do not edit by hand.
import type { RoleTaxonomy } from "../roleTypes";

export const ROLE_TAXONOMY: RoleTaxonomy = {
 "groups": [
  {
   "id": "it",
   "name": "기술·IT"
  },
  {
   "id": "biz",
   "name": "경영·사무"
  },
  {
   "id": "fin",
   "name": "금융·회계"
  },
  {
   "id": "mkt",
   "name": "마케팅·영업·유통"
  },
  {
   "id": "mfg",
   "name": "제조·생산·품질"
  },
  {
   "id": "rnd",
   "name": "연구개발·엔지니어링"
  },
  {
   "id": "med",
   "name": "의료·보건"
  },
  {
   "id": "edu",
   "name": "교육·복지·상담"
  },
  {
   "id": "pub",
   "name": "공공·공기업"
  },
  {
   "id": "svc",
   "name": "서비스·관광·항공"
  },
  {
   "id": "media",
   "name": "디자인·미디어·문화"
  },
  {
   "id": "etc",
   "name": "기타 전문직"
  }
 ],
 "domains": [
  {
   "id": "strategy",
   "name": "경영·전략",
   "nameEn": "Strategy & Management",
   "group": "biz",
   "q": 191
  },
  {
   "id": "hr",
   "name": "인사·노무",
   "nameEn": "HR & Labor Relations",
   "group": "biz",
   "q": 175
  },
  {
   "id": "admin",
   "name": "총무·사무",
   "nameEn": "General Affairs & Office",
   "group": "biz",
   "q": 94
  },
  {
   "id": "accounting",
   "name": "회계·재무·세무",
   "nameEn": "Accounting, Finance & Tax",
   "group": "fin",
   "q": 237
  },
  {
   "id": "finance",
   "name": "금융·은행·보험",
   "nameEn": "Banking, Securities & Insurance",
   "group": "fin",
   "q": 272
  },
  {
   "id": "legal",
   "name": "법무·컴플라이언스",
   "nameEn": "Legal & Compliance",
   "group": "biz",
   "q": 143
  },
  {
   "id": "marketing",
   "name": "마케팅·광고·브랜드",
   "nameEn": "Marketing, Advertising & Brand",
   "group": "mkt",
   "q": 249
  },
  {
   "id": "sales",
   "name": "영업·영업관리",
   "nameEn": "Sales",
   "group": "mkt",
   "q": 186
  },
  {
   "id": "trade",
   "name": "해외영업·무역",
   "nameEn": "Overseas Sales & Trade",
   "group": "mkt",
   "q": 82
  },
  {
   "id": "md",
   "name": "MD·상품",
   "nameEn": "Merchandising",
   "group": "mkt",
   "q": 93
  },
  {
   "id": "purchasing",
   "name": "구매",
   "nameEn": "Purchasing",
   "group": "mfg",
   "q": 89
  },
  {
   "id": "logistics",
   "name": "물류·SCM",
   "nameEn": "Logistics & SCM",
   "group": "mfg",
   "q": 115
  },
  {
   "id": "cs",
   "name": "고객지원·CS",
   "nameEn": "Customer Support",
   "group": "svc",
   "q": 81
  },
  {
   "id": "product",
   "name": "서비스기획·PM·PO",
   "nameEn": "Product Management",
   "group": "it",
   "q": 104
  },
  {
   "id": "software",
   "name": "소프트웨어 개발",
   "nameEn": "Software Engineering",
   "group": "it",
   "q": 166
  },
  {
   "id": "data_ai",
   "name": "데이터·AI",
   "nameEn": "Data & AI",
   "group": "it",
   "q": 185
  },
  {
   "id": "infra",
   "name": "보안·인프라·클라우드",
   "nameEn": "Security, Infrastructure & Cloud",
   "group": "it",
   "q": 190
  },
  {
   "id": "game",
   "name": "게임",
   "nameEn": "Games",
   "group": "it",
   "q": 121
  },
  {
   "id": "design",
   "name": "디자인",
   "nameEn": "Design",
   "group": "media",
   "q": 175
  },
  {
   "id": "content",
   "name": "콘텐츠·미디어",
   "nameEn": "Content & Media",
   "group": "media",
   "q": 96
  },
  {
   "id": "broadcast",
   "name": "영상·방송",
   "nameEn": "Video & Broadcasting",
   "group": "media",
   "q": 114
  },
  {
   "id": "rnd",
   "name": "연구개발",
   "nameEn": "Research & Development",
   "group": "rnd",
   "q": 78
  },
  {
   "id": "electronics",
   "name": "반도체·전자",
   "nameEn": "Semiconductors & Electronics",
   "group": "rnd",
   "q": 176
  },
  {
   "id": "mechanical",
   "name": "기계·자동차",
   "nameEn": "Mechanical & Automotive",
   "group": "rnd",
   "q": 96
  },
  {
   "id": "chemical",
   "name": "화학·소재",
   "nameEn": "Chemicals & Materials",
   "group": "rnd",
   "q": 96
  },
  {
   "id": "bio",
   "name": "바이오·제약",
   "nameEn": "Bio & Pharma",
   "group": "rnd",
   "q": 115
  },
  {
   "id": "environment",
   "name": "환경",
   "nameEn": "Environment",
   "group": "rnd",
   "q": 80
  },
  {
   "id": "energy",
   "name": "에너지",
   "nameEn": "Energy",
   "group": "rnd",
   "q": 79
  },
  {
   "id": "architecture",
   "name": "건축",
   "nameEn": "Architecture",
   "group": "rnd",
   "q": 98
  },
  {
   "id": "civil",
   "name": "토목",
   "nameEn": "Civil Engineering",
   "group": "rnd",
   "q": 124
  },
  {
   "id": "safety",
   "name": "안전",
   "nameEn": "Safety",
   "group": "mfg",
   "q": 98
  },
  {
   "id": "production",
   "name": "생산·제조",
   "nameEn": "Production & Manufacturing",
   "group": "mfg",
   "q": 100
  },
  {
   "id": "quality",
   "name": "품질",
   "nameEn": "Quality",
   "group": "mfg",
   "q": 96
  },
  {
   "id": "process",
   "name": "공정",
   "nameEn": "Process Engineering",
   "group": "mfg",
   "q": 79
  },
  {
   "id": "science",
   "name": "연구원·과학",
   "nameEn": "Science & Research",
   "group": "rnd",
   "q": 80
  },
  {
   "id": "education",
   "name": "교육",
   "nameEn": "Education",
   "group": "edu",
   "q": 178
  },
  {
   "id": "medical",
   "name": "의료·간호",
   "nameEn": "Medicine & Nursing",
   "group": "med",
   "q": 166
  },
  {
   "id": "health_tech",
   "name": "보건·의료기술",
   "nameEn": "Allied Health",
   "group": "med",
   "q": 170
  },
  {
   "id": "welfare",
   "name": "사회복지",
   "nameEn": "Social Welfare",
   "group": "edu",
   "q": 92
  },
  {
   "id": "counseling",
   "name": "상담",
   "nameEn": "Counseling",
   "group": "edu",
   "q": 76
  },
  {
   "id": "hospitality",
   "name": "호텔·관광",
   "nameEn": "Hotels & Tourism",
   "group": "svc",
   "q": 113
  },
  {
   "id": "aviation",
   "name": "항공",
   "nameEn": "Aviation",
   "group": "svc",
   "q": 112
  },
  {
   "id": "food",
   "name": "외식·식음료",
   "nameEn": "Food & Beverage",
   "group": "svc",
   "q": 139
  },
  {
   "id": "retail",
   "name": "유통·리테일",
   "nameEn": "Retail & Distribution",
   "group": "mkt",
   "q": 99
  },
  {
   "id": "public_admin",
   "name": "공공행정",
   "nameEn": "Public Administration",
   "group": "pub",
   "q": 150
  },
  {
   "id": "public_enterprise",
   "name": "공기업",
   "nameEn": "Public Enterprises",
   "group": "pub",
   "q": 129
  },
  {
   "id": "nonprofit",
   "name": "비영리·공공기관",
   "nameEn": "Nonprofits & Public Institutions",
   "group": "pub",
   "q": 76
  },
  {
   "id": "research_institute",
   "name": "연구기관",
   "nameEn": "Research Institutes",
   "group": "pub",
   "q": 76
  },
  {
   "id": "culture_arts",
   "name": "문화·예술",
   "nameEn": "Culture & Arts",
   "group": "media",
   "q": 77
  },
  {
   "id": "sports",
   "name": "스포츠",
   "nameEn": "Sports",
   "group": "svc",
   "q": 76
  },
  {
   "id": "professional",
   "name": "기타 전문직",
   "nameEn": "Other Professions",
   "group": "etc",
   "q": 154
  }
 ],
 "families": [
  {
   "id": "strategy_planning",
   "domain": "strategy",
   "name": "전략·기획",
   "nameEn": "Strategy & Planning",
   "dept": "전략기획팀",
   "archetype": "strategy_business",
   "q": 130
  },
  {
   "id": "investment_ir",
   "domain": "strategy",
   "name": "투자·IR",
   "nameEn": "Investment & IR",
   "dept": "재무전략팀",
   "archetype": "strategy_business",
   "q": 61
  },
  {
   "id": "hr_people",
   "domain": "hr",
   "name": "인사·HR",
   "nameEn": "Human Resources",
   "dept": "인사팀",
   "archetype": "hr_people",
   "q": 130
  },
  {
   "id": "labor",
   "domain": "hr",
   "name": "노무",
   "nameEn": "Labor Relations",
   "dept": "인사팀",
   "archetype": "hr_people",
   "q": 45
  },
  {
   "id": "general_affairs",
   "domain": "admin",
   "name": "총무·사무",
   "nameEn": "General Affairs & Office",
   "dept": "경영지원팀",
   "archetype": "admin_support",
   "q": 94
  },
  {
   "id": "accounting",
   "domain": "accounting",
   "name": "회계",
   "nameEn": "Accounting",
   "dept": "재무회계팀",
   "archetype": "finance_accounting",
   "q": 79
  },
  {
   "id": "corporate_finance",
   "domain": "accounting",
   "name": "재무",
   "nameEn": "Corporate Finance",
   "dept": "재무팀",
   "archetype": "finance_accounting",
   "q": 79
  },
  {
   "id": "tax",
   "domain": "accounting",
   "name": "세무·감사",
   "nameEn": "Tax & Audit",
   "dept": "세무팀",
   "archetype": "finance_accounting",
   "q": 79
  },
  {
   "id": "banking",
   "domain": "finance",
   "name": "은행",
   "nameEn": "Banking",
   "dept": "영업점",
   "archetype": "finance_markets",
   "q": 97
  },
  {
   "id": "securities_am",
   "domain": "finance",
   "name": "증권·자산운용",
   "nameEn": "Securities & Asset Management",
   "dept": "투자사업부",
   "archetype": "finance_markets",
   "q": 96
  },
  {
   "id": "insurance",
   "domain": "finance",
   "name": "보험",
   "nameEn": "Insurance",
   "dept": "보험사업부",
   "archetype": "finance_markets",
   "q": 79
  },
  {
   "id": "legal",
   "domain": "legal",
   "name": "법무",
   "nameEn": "Legal",
   "dept": "법무팀",
   "archetype": "legal_compliance",
   "q": 81
  },
  {
   "id": "compliance",
   "domain": "legal",
   "name": "컴플라이언스",
   "nameEn": "Compliance",
   "dept": "준법감시팀",
   "archetype": "legal_compliance",
   "q": 62
  },
  {
   "id": "digital_marketing",
   "domain": "marketing",
   "name": "디지털 마케팅",
   "nameEn": "Digital Marketing",
   "dept": "마케팅팀",
   "archetype": "marketing_growth",
   "q": 96
  },
  {
   "id": "brand",
   "domain": "marketing",
   "name": "브랜드·PR",
   "nameEn": "Brand & PR",
   "dept": "브랜드팀",
   "archetype": "marketing_growth",
   "q": 94
  },
  {
   "id": "advertising",
   "domain": "marketing",
   "name": "광고",
   "nameEn": "Advertising",
   "dept": "광고기획팀",
   "archetype": "marketing_growth",
   "q": 59
  },
  {
   "id": "sales",
   "domain": "sales",
   "name": "영업",
   "nameEn": "Sales",
   "dept": "영업팀",
   "archetype": "sales_customer",
   "q": 126
  },
  {
   "id": "sales_ops",
   "domain": "sales",
   "name": "영업관리",
   "nameEn": "Sales Management",
   "dept": "영업관리팀",
   "archetype": "sales_customer",
   "q": 60
  },
  {
   "id": "trade",
   "domain": "trade",
   "name": "해외영업·무역",
   "nameEn": "Overseas Sales & Trade",
   "dept": "해외영업팀",
   "archetype": "sales_customer",
   "q": 82
  },
  {
   "id": "merchandising",
   "domain": "md",
   "name": "MD·상품기획",
   "nameEn": "Merchandising",
   "dept": "상품기획팀",
   "archetype": "commerce_md",
   "q": 93
  },
  {
   "id": "purchasing",
   "domain": "purchasing",
   "name": "구매·조달",
   "nameEn": "Purchasing & Procurement",
   "dept": "구매팀",
   "archetype": "supply_ops",
   "q": 89
  },
  {
   "id": "scm",
   "domain": "logistics",
   "name": "물류·SCM",
   "nameEn": "Logistics & Supply Chain",
   "dept": "SCM팀",
   "archetype": "supply_ops",
   "q": 115
  },
  {
   "id": "customer_support",
   "domain": "cs",
   "name": "고객지원",
   "nameEn": "Customer Support",
   "dept": "고객경험팀",
   "archetype": "service_hospitality",
   "q": 81
  },
  {
   "id": "product",
   "domain": "product",
   "name": "서비스기획·PM",
   "nameEn": "Product",
   "dept": "프로덕트팀",
   "archetype": "product_planning",
   "q": 104
  },
  {
   "id": "software",
   "domain": "software",
   "name": "소프트웨어 개발",
   "nameEn": "Software Development",
   "dept": "개발팀",
   "archetype": "tech_dev",
   "q": 166
  },
  {
   "id": "data",
   "domain": "data_ai",
   "name": "데이터",
   "nameEn": "Data",
   "dept": "데이터팀",
   "archetype": "data_analytic",
   "q": 77
  },
  {
   "id": "ai",
   "domain": "data_ai",
   "name": "AI·머신러닝",
   "nameEn": "AI & Machine Learning",
   "dept": "AI연구소",
   "archetype": "tech_dev",
   "q": 108
  },
  {
   "id": "infra",
   "domain": "infra",
   "name": "인프라·클라우드",
   "nameEn": "Infrastructure & Cloud",
   "dept": "인프라팀",
   "archetype": "tech_dev",
   "q": 128
  },
  {
   "id": "security",
   "domain": "infra",
   "name": "정보보안",
   "nameEn": "Information Security",
   "dept": "정보보안팀",
   "archetype": "tech_dev",
   "q": 62
  },
  {
   "id": "game",
   "domain": "game",
   "name": "게임",
   "nameEn": "Game Development",
   "dept": "게임개발팀",
   "archetype": "tech_dev",
   "q": 61
  },
  {
   "id": "game_business",
   "domain": "game",
   "name": "게임 기획·사업",
   "nameEn": "Game Design & Business",
   "dept": "게임사업팀",
   "archetype": "product_planning",
   "q": 60
  },
  {
   "id": "digital_design",
   "domain": "design",
   "name": "UX·UI·프로덕트 디자인",
   "nameEn": "Digital Product Design",
   "dept": "디자인팀",
   "archetype": "design_creative",
   "q": 79
  },
  {
   "id": "visual_design",
   "domain": "design",
   "name": "시각·산업 디자인",
   "nameEn": "Visual & Industrial Design",
   "dept": "디자인팀",
   "archetype": "design_creative",
   "q": 96
  },
  {
   "id": "content",
   "domain": "content",
   "name": "콘텐츠",
   "nameEn": "Content",
   "dept": "콘텐츠팀",
   "archetype": "media_content",
   "q": 96
  },
  {
   "id": "broadcast",
   "domain": "broadcast",
   "name": "영상·방송",
   "nameEn": "Video & Broadcasting",
   "dept": "제작팀",
   "archetype": "media_content",
   "q": 114
  },
  {
   "id": "rnd",
   "domain": "rnd",
   "name": "연구개발",
   "nameEn": "R&D",
   "dept": "R&D센터",
   "archetype": "engineering_design",
   "q": 78
  },
  {
   "id": "semiconductor",
   "domain": "electronics",
   "name": "반도체",
   "nameEn": "Semiconductors",
   "dept": "반도체사업부",
   "archetype": "manufacturing_quality",
   "q": 98
  },
  {
   "id": "electronics",
   "domain": "electronics",
   "name": "전기·전자",
   "nameEn": "Electrical & Electronics",
   "dept": "전자개발팀",
   "archetype": "engineering_design",
   "q": 78
  },
  {
   "id": "mechanical",
   "domain": "mechanical",
   "name": "기계·자동차",
   "nameEn": "Mechanical & Automotive",
   "dept": "기계설계팀",
   "archetype": "engineering_design",
   "q": 96
  },
  {
   "id": "chemical",
   "domain": "chemical",
   "name": "화학·소재",
   "nameEn": "Chemicals & Materials",
   "dept": "소재연구소",
   "archetype": "research_science",
   "q": 96
  },
  {
   "id": "bio_pharma",
   "domain": "bio",
   "name": "바이오·제약",
   "nameEn": "Bio & Pharma",
   "dept": "연구소",
   "archetype": "research_science",
   "q": 115
  },
  {
   "id": "environment",
   "domain": "environment",
   "name": "환경",
   "nameEn": "Environment",
   "dept": "환경안전팀",
   "archetype": "safety_environment",
   "q": 80
  },
  {
   "id": "energy",
   "domain": "energy",
   "name": "에너지",
   "nameEn": "Energy",
   "dept": "발전사업팀",
   "archetype": "manufacturing_quality",
   "q": 79
  },
  {
   "id": "architecture",
   "domain": "architecture",
   "name": "건축",
   "nameEn": "Architecture",
   "dept": "건축사업팀",
   "archetype": "field_construction",
   "q": 98
  },
  {
   "id": "civil",
   "domain": "civil",
   "name": "토목",
   "nameEn": "Civil Engineering",
   "dept": "토목사업팀",
   "archetype": "field_construction",
   "q": 79
  },
  {
   "id": "landscape",
   "domain": "civil",
   "name": "조경",
   "nameEn": "Landscape",
   "dept": "조경팀",
   "archetype": "field_construction",
   "q": 45
  },
  {
   "id": "safety",
   "domain": "safety",
   "name": "안전·보건",
   "nameEn": "Safety & Health",
   "dept": "안전보건팀",
   "archetype": "safety_environment",
   "q": 98
  },
  {
   "id": "production",
   "domain": "production",
   "name": "생산·제조",
   "nameEn": "Production",
   "dept": "생산팀",
   "archetype": "manufacturing_quality",
   "q": 100
  },
  {
   "id": "quality",
   "domain": "quality",
   "name": "품질",
   "nameEn": "Quality",
   "dept": "품질팀",
   "archetype": "manufacturing_quality",
   "q": 96
  },
  {
   "id": "process",
   "domain": "process",
   "name": "공정",
   "nameEn": "Process",
   "dept": "공정기술팀",
   "archetype": "manufacturing_quality",
   "q": 79
  },
  {
   "id": "science",
   "domain": "science",
   "name": "기초·응용과학",
   "nameEn": "Science",
   "dept": "연구소",
   "archetype": "research_science",
   "q": 80
  },
  {
   "id": "school",
   "domain": "education",
   "name": "학교 교육",
   "nameEn": "School Teaching",
   "dept": "교무부",
   "archetype": "education",
   "q": 99
  },
  {
   "id": "edu_business",
   "domain": "education",
   "name": "교육 서비스",
   "nameEn": "Education Services",
   "dept": "교육사업팀",
   "archetype": "education",
   "q": 79
  },
  {
   "id": "nursing",
   "domain": "medical",
   "name": "간호",
   "nameEn": "Nursing",
   "dept": "간호부",
   "archetype": "clinical_care",
   "q": 73
  },
  {
   "id": "medical_staff",
   "domain": "medical",
   "name": "의료",
   "nameEn": "Medical",
   "dept": "진료부",
   "archetype": "clinical_care",
   "q": 93
  },
  {
   "id": "allied_health",
   "domain": "health_tech",
   "name": "보건의료기술",
   "nameEn": "Allied Health",
   "dept": "의료기술부",
   "archetype": "clinical_care",
   "q": 126
  },
  {
   "id": "public_health",
   "domain": "health_tech",
   "name": "보건",
   "nameEn": "Public Health",
   "dept": "보건사업팀",
   "archetype": "clinical_care",
   "q": 44
  },
  {
   "id": "welfare",
   "domain": "welfare",
   "name": "사회복지",
   "nameEn": "Social Welfare",
   "dept": "사회복지팀",
   "archetype": "social_care",
   "q": 92
  },
  {
   "id": "counseling",
   "domain": "counseling",
   "name": "상담",
   "nameEn": "Counseling",
   "dept": "상담센터",
   "archetype": "social_care",
   "q": 76
  },
  {
   "id": "hotel_tourism",
   "domain": "hospitality",
   "name": "호텔·관광",
   "nameEn": "Hotels & Tourism",
   "dept": "객실팀",
   "archetype": "service_hospitality",
   "q": 113
  },
  {
   "id": "aviation",
   "domain": "aviation",
   "name": "항공",
   "nameEn": "Aviation",
   "dept": "운항·객실본부",
   "archetype": "service_hospitality",
   "q": 112
  },
  {
   "id": "food_service",
   "domain": "food",
   "name": "외식",
   "nameEn": "Food Service",
   "dept": "외식사업팀",
   "archetype": "service_hospitality",
   "q": 78
  },
  {
   "id": "food_industry",
   "domain": "food",
   "name": "식품",
   "nameEn": "Food Industry",
   "dept": "식품연구소",
   "archetype": "research_science",
   "q": 61
  },
  {
   "id": "retail",
   "domain": "retail",
   "name": "유통·리테일",
   "nameEn": "Retail",
   "dept": "영업관리팀",
   "archetype": "sales_customer",
   "q": 99
  },
  {
   "id": "civil_service",
   "domain": "public_admin",
   "name": "공무원",
   "nameEn": "Civil Service",
   "dept": "행정지원과",
   "archetype": "public_service",
   "q": 150
  },
  {
   "id": "public_enterprise",
   "domain": "public_enterprise",
   "name": "공기업",
   "nameEn": "Public Enterprises",
   "dept": "인재개발원",
   "archetype": "public_service",
   "q": 129
  },
  {
   "id": "nonprofit",
   "domain": "nonprofit",
   "name": "비영리·공공기관",
   "nameEn": "Nonprofits & Public Institutions",
   "dept": "사업운영팀",
   "archetype": "public_service",
   "q": 76
  },
  {
   "id": "research_institute",
   "domain": "research_institute",
   "name": "연구기관",
   "nameEn": "Research Institutes",
   "dept": "연구기획실",
   "archetype": "research_science",
   "q": 76
  },
  {
   "id": "culture_arts",
   "domain": "culture_arts",
   "name": "문화·예술",
   "nameEn": "Culture & Arts",
   "dept": "기획팀",
   "archetype": "media_content",
   "q": 77
  },
  {
   "id": "sports",
   "domain": "sports",
   "name": "스포츠",
   "nameEn": "Sports",
   "dept": "스포츠사업팀",
   "archetype": "service_hospitality",
   "q": 76
  },
  {
   "id": "licensed",
   "domain": "professional",
   "name": "전문자격",
   "nameEn": "Licensed Professions",
   "dept": "전문위원",
   "archetype": "legal_compliance",
   "q": 94
  },
  {
   "id": "language_realestate",
   "domain": "professional",
   "name": "통번역·부동산",
   "nameEn": "Translation & Real Estate",
   "dept": "전문위원",
   "archetype": "media_content",
   "q": 60
  }
 ],
 "roles": [
  {
   "id": "strategy_planner",
   "family": "strategy_planning",
   "ko": "전략기획",
   "en": "Strategy Planner",
   "aliases": [
    "전략기획",
    "Strategy Planner",
    "전략기획팀",
    "전략기획 담당자",
    "전략팀",
    "경영전략",
    "Corporate Strategy",
    "전략 담당"
   ],
   "q": 17
  },
  {
   "id": "business_planner",
   "family": "strategy_planning",
   "ko": "사업기획",
   "en": "Business Planner",
   "aliases": [
    "사업기획",
    "Business Planner",
    "사업기획팀",
    "사업계획",
    "사업관리",
    "Business Planning",
    "사업전략"
   ],
   "q": 17
  },
  {
   "id": "corporate_planner",
   "family": "strategy_planning",
   "ko": "경영기획",
   "en": "Corporate Planning",
   "aliases": [
    "경영기획",
    "Corporate Planning",
    "경영기획팀",
    "기획조정",
    "경영관리 기획",
    "경영계획",
    "기획예산"
   ],
   "q": 17
  },
  {
   "id": "business_management",
   "family": "strategy_planning",
   "ko": "경영관리·경영지원",
   "en": "Business Management",
   "aliases": [
    "경영관리·경영지원",
    "Business Management",
    "경영지원",
    "경영지원팀",
    "경영관리팀",
    "Business Support",
    "관리팀"
   ],
   "q": 17
  },
  {
   "id": "new_business",
   "family": "strategy_planning",
   "ko": "신사업기획",
   "en": "New Business Development",
   "aliases": [
    "신사업기획",
    "New Business Development",
    "신사업개발",
    "신사업팀",
    "사업개발",
    "BD",
    "신규사업"
   ],
   "q": 17
  },
  {
   "id": "management_consultant",
   "family": "strategy_planning",
   "ko": "경영컨설턴트",
   "en": "Management Consultant",
   "aliases": [
    "경영컨설턴트",
    "Management Consultant",
    "컨설턴트",
    "전략컨설턴트",
    "경영컨설팅",
    "Strategy Consultant",
    "Business Analyst"
   ],
   "q": 17
  },
  {
   "id": "ir_manager",
   "family": "investment_ir",
   "ko": "IR",
   "en": "Investor Relations",
   "aliases": [
    "IR",
    "Investor Relations",
    "IR 담당자",
    "IR팀",
    "투자자관계",
    "IRO",
    "IR·공시"
   ],
   "q": 17
  },
  {
   "id": "corporate_investment",
   "family": "investment_ir",
   "ko": "기업투자·M&A",
   "en": "Corporate Investment / M&A",
   "aliases": [
    "기업투자·M&A",
    "Corporate Investment / M&A",
    "기업투자",
    "M&A",
    "인수합병",
    "전략투자",
    "CVC",
    "Corporate Development",
    "투자 담당"
   ],
   "q": 17
  },
  {
   "id": "recruiter",
   "family": "hr_people",
   "ko": "채용 담당",
   "en": "Recruiter / Talent Acquisition",
   "aliases": [
    "채용 담당",
    "Recruiter / Talent Acquisition",
    "채용",
    "채용담당자",
    "리크루터",
    "채용팀",
    "Talent Acquisition",
    "Recruiter",
    "TA"
   ],
   "q": 17
  },
  {
   "id": "hr_planner",
   "family": "hr_people",
   "ko": "인사기획",
   "en": "HR Planning",
   "aliases": [
    "인사기획",
    "HR Planning",
    "인사제도",
    "HR 기획",
    "인사전략",
    "HRM 기획"
   ],
   "q": 17
  },
  {
   "id": "hrd",
   "family": "hr_people",
   "ko": "HRD·교육",
   "en": "HR Development",
   "aliases": [
    "HRD·교육",
    "HR Development",
    "교육 담당",
    "인재개발",
    "교육팀",
    "L&D",
    "Learning & Development",
    "사내교육",
    "교육 담당자"
   ],
   "q": 17
  },
  {
   "id": "hrbp",
   "family": "hr_people",
   "ko": "HRBP",
   "en": "HR Business Partner",
   "aliases": [
    "HR BP",
    "HR Business Partner",
    "HR 비즈니스 파트너",
    "사업부 인사",
    "현업 인사"
   ],
   "q": 17
  },
  {
   "id": "compensation",
   "family": "hr_people",
   "ko": "보상·평가(C&B)",
   "en": "Compensation & Benefits",
   "aliases": [
    "보상·평가(C&B)",
    "Compensation & Benefits",
    "보상·평가",
    "C&B",
    "평가",
    "평가보상",
    "보상 담당",
    "Total Rewards",
    "급여·복리후생"
   ],
   "q": 17
  },
  {
   "id": "org_culture",
   "family": "hr_people",
   "ko": "조직문화",
   "en": "Organizational Culture",
   "aliases": [
    "조직문화",
    "Organizational Culture",
    "조직문화 담당",
    "컬처팀",
    "조직개발",
    "OD",
    "Culture & Engagement",
    "사내 커뮤니케이션"
   ],
   "q": 17
  },
  {
   "id": "labor_relations",
   "family": "labor",
   "ko": "노무 담당",
   "en": "Labor Relations Specialist",
   "aliases": [
    "노무 담당",
    "Labor Relations Specialist",
    "노무",
    "노사관계",
    "노사협력",
    "노무관리",
    "Labor Relations",
    "Employee Relations",
    "ER"
   ],
   "q": 18
  },
  {
   "id": "general_affairs",
   "family": "general_affairs",
   "ko": "총무",
   "en": "General Affairs",
   "aliases": [
    "총무",
    "General Affairs",
    "총무팀",
    "총무 담당",
    "인사총무",
    "GA",
    "경영지원 총무"
   ],
   "q": 17
  },
  {
   "id": "office_admin",
   "family": "general_affairs",
   "ko": "사무·행정지원",
   "en": "Office Administrator",
   "aliases": [
    "사무·행정지원",
    "Office Administrator",
    "행정지원",
    "사무직",
    "사무행정",
    "사무보조",
    "Administrative Assistant"
   ],
   "q": 16
  },
  {
   "id": "secretary",
   "family": "general_affairs",
   "ko": "비서",
   "en": "Executive Assistant",
   "aliases": [
    "비서",
    "Executive Assistant",
    "임원비서",
    "수행비서",
    "비서실",
    "Secretary",
    "EA"
   ],
   "q": 17
  },
  {
   "id": "facility_asset",
   "family": "general_affairs",
   "ko": "자산·시설관리",
   "en": "Facility & Asset Management",
   "aliases": [
    "자산·시설관리",
    "Facility & Asset Management",
    "자산",
    "시설관리",
    "시설 담당",
    "FM",
    "Facility Management",
    "자산·시설",
    "사옥관리",
    "부동산 관리"
   ],
   "q": 17
  },
  {
   "id": "accountant",
   "family": "accounting",
   "ko": "회계(재무회계)",
   "en": "Accountant",
   "aliases": [
    "회계(재무회계)",
    "Accountant",
    "회계",
    "재무회계",
    "회계 담당자",
    "회계팀",
    "결산 담당",
    "Financial Accountant",
    "GL Accountant",
    "Accounting"
   ],
   "q": 17
  },
  {
   "id": "cost_accountant",
   "family": "accounting",
   "ko": "관리회계·원가",
   "en": "Management / Cost Accountant",
   "aliases": [
    "관리회계·원가",
    "Management / Cost Accountant",
    "관리회계",
    "원가",
    "원가회계",
    "원가 담당자",
    "원가팀",
    "Cost Accountant",
    "Management Accountant"
   ],
   "q": 17
  },
  {
   "id": "internal_control",
   "family": "accounting",
   "ko": "내부회계·내부통제",
   "en": "Internal Control",
   "aliases": [
    "내부회계·내부통제",
    "Internal Control",
    "내부회계",
    "내부회계관리",
    "ICFR",
    "SOX",
    "내부회계관리제도 담당"
   ],
   "q": 17
  },
  {
   "id": "finance_manager",
   "family": "corporate_finance",
   "ko": "재무",
   "en": "Corporate Finance",
   "aliases": [
    "재무",
    "Corporate Finance",
    "재무관리",
    "재무팀",
    "재무 담당자",
    "기업재무",
    "Finance Manager"
   ],
   "q": 17
  },
  {
   "id": "treasury",
   "family": "corporate_finance",
   "ko": "자금",
   "en": "Treasury",
   "aliases": [
    "자금",
    "Treasury",
    "자금팀",
    "자금 담당자",
    "자금관리",
    "트레저리",
    "Cash Management"
   ],
   "q": 17
  },
  {
   "id": "fpa",
   "family": "corporate_finance",
   "ko": "FP&A",
   "en": "FP&A Analyst",
   "aliases": [
    "FP&A",
    "FP&A Analyst",
    "경영분석",
    "재무기획",
    "예산 담당",
    "Financial Planning & Analysis"
   ],
   "q": 17
  },
  {
   "id": "tax_specialist",
   "family": "tax",
   "ko": "세무",
   "en": "Tax Specialist",
   "aliases": [
    "세무",
    "Tax Specialist",
    "세무 담당자",
    "세무팀",
    "기업 세무",
    "택스",
    "Tax Accountant"
   ],
   "q": 17
  },
  {
   "id": "auditor",
   "family": "tax",
   "ko": "회계감사·공인회계사",
   "en": "Auditor / CPA",
   "aliases": [
    "회계감사·공인회계사",
    "Auditor / CPA",
    "회계감사",
    "공인회계사",
    "CPA",
    "외부감사인",
    "감사본부",
    "Auditor",
    "Audit Associate"
   ],
   "q": 17
  },
  {
   "id": "internal_auditor",
   "family": "tax",
   "ko": "내부감사",
   "en": "Internal Auditor",
   "aliases": [
    "내부감사",
    "Internal Auditor",
    "감사팀",
    "감사실",
    "경영감사",
    "Internal Audit"
   ],
   "q": 17
  },
  {
   "id": "bank_teller",
   "family": "banking",
   "ko": "은행원(리테일)",
   "en": "Retail Banker",
   "aliases": [
    "은행원(리테일)",
    "Retail Banker",
    "은행원",
    "리테일",
    "개인금융",
    "창구",
    "텔러",
    "영업점 직원",
    "Bank Teller"
   ],
   "q": 17
  },
  {
   "id": "private_banker",
   "family": "banking",
   "ko": "PB",
   "en": "Private Banker",
   "aliases": [
    "PB",
    "Private Banker",
    "프라이빗뱅커",
    "WM",
    "VIP 자산관리",
    "Wealth Manager"
   ],
   "q": 17
  },
  {
   "id": "relationship_manager",
   "family": "banking",
   "ko": "기업금융 RM",
   "en": "Corporate Relationship Manager",
   "aliases": [
    "기업금융 RM",
    "Corporate Relationship Manager",
    "기업금융",
    "RM",
    "기업 여신 담당",
    "Relationship Manager",
    "Corporate Banker"
   ],
   "q": 17
  },
  {
   "id": "credit_analyst",
   "family": "banking",
   "ko": "여신심사",
   "en": "Credit Analyst",
   "aliases": [
    "여신심사",
    "Credit Analyst",
    "심사역",
    "신용분석",
    "신용평가",
    "Credit Officer"
   ],
   "q": 17
  },
  {
   "id": "securities",
   "family": "securities_am",
   "ko": "증권(리서치·세일즈)",
   "en": "Securities Research & Sales",
   "aliases": [
    "증권(리서치·세일즈)",
    "Securities Research & Sales",
    "증권",
    "세일즈",
    "애널리스트",
    "증권 세일즈",
    "기관영업",
    "Equity Research",
    "Securities Sales"
   ],
   "q": 17
  },
  {
   "id": "investment_banker",
   "family": "securities_am",
   "ko": "IB(투자은행)",
   "en": "Investment Banker",
   "aliases": [
    "IB(투자은행)",
    "Investment Banker",
    "IB",
    "투자은행",
    "기업금융(IB)",
    "ECM",
    "DCM",
    "M&A 자문",
    "IB Analyst"
   ],
   "q": 17
  },
  {
   "id": "asset_manager",
   "family": "securities_am",
   "ko": "자산운용",
   "en": "Asset Manager",
   "aliases": [
    "자산운용",
    "Asset Manager",
    "펀드매니저",
    "운용역",
    "포트폴리오 매니저",
    "Portfolio Manager",
    "Fund Manager"
   ],
   "q": 17
  },
  {
   "id": "risk_manager",
   "family": "securities_am",
   "ko": "리스크관리",
   "en": "Risk Manager",
   "aliases": [
    "리스크관리",
    "Risk Manager",
    "리스크 매니저",
    "위험관리",
    "시장리스크",
    "신용리스크",
    "Risk Analyst"
   ],
   "q": 17
  },
  {
   "id": "underwriter",
   "family": "insurance",
   "ko": "보험심사(언더라이팅)",
   "en": "Underwriter",
   "aliases": [
    "보험심사(언더라이팅)",
    "Underwriter",
    "언더라이팅",
    "언더라이터",
    "계약심사",
    "인수심사"
   ],
   "q": 17
  },
  {
   "id": "actuary",
   "family": "insurance",
   "ko": "보험계리",
   "en": "Actuary",
   "aliases": [
    "보험계리",
    "Actuary",
    "계리사",
    "보험계리사",
    "계리",
    "상품계리",
    "Actuarial Analyst"
   ],
   "q": 17
  },
  {
   "id": "claims_adjuster",
   "family": "insurance",
   "ko": "보상·손해사정",
   "en": "Claims Adjuster",
   "aliases": [
    "보상·손해사정",
    "Claims Adjuster",
    "손해사정",
    "손해사정사",
    "보상 담당자",
    "클레임",
    "Loss Adjuster"
   ],
   "q": 17
  },
  {
   "id": "corporate_legal",
   "family": "legal",
   "ko": "기업법무",
   "en": "In-house Legal Counsel",
   "aliases": [
    "기업법무",
    "In-house Legal Counsel",
    "사내법무",
    "법무팀",
    "법무 담당자",
    "사내변호사",
    "법무 매니저",
    "In-house Counsel",
    "Corporate Legal"
   ],
   "q": 17
  },
  {
   "id": "lawyer",
   "family": "legal",
   "ko": "변호사",
   "en": "Lawyer",
   "aliases": [
    "변호사",
    "Lawyer",
    "송무 변호사",
    "자문 변호사",
    "법률자문",
    "기관 변호사",
    "Attorney",
    "Legal Counsel"
   ],
   "q": 17
  },
  {
   "id": "ip_specialist",
   "family": "legal",
   "ko": "특허·IP 관리",
   "en": "IP Specialist",
   "aliases": [
    "특허·IP 관리",
    "IP Specialist",
    "특허",
    "IP 관리",
    "특허 관리",
    "지식재산 관리",
    "특허팀",
    "IP 담당자",
    "특허 엔지니어",
    "Patent Manager"
   ],
   "q": 18
  },
  {
   "id": "compliance_officer",
   "family": "compliance",
   "ko": "컴플라이언스(준법감시)",
   "en": "Compliance Officer",
   "aliases": [
    "컴플라이언스(준법감시)",
    "Compliance Officer",
    "컴플라이언스",
    "준법감시",
    "준법감시인",
    "준법지원",
    "윤리경영",
    "Compliance Manager"
   ],
   "q": 16
  },
  {
   "id": "privacy_officer",
   "family": "compliance",
   "ko": "개인정보보호",
   "en": "Privacy Officer",
   "aliases": [
    "개인정보보호",
    "Privacy Officer",
    "개인정보보호 담당자",
    "프라이버시",
    "개인정보 관리",
    "Privacy Manager",
    "DPO"
   ],
   "q": 17
  },
  {
   "id": "performance_marketer",
   "family": "digital_marketing",
   "ko": "퍼포먼스 마케팅",
   "en": "Performance Marketer",
   "aliases": [
    "퍼포먼스 마케팅",
    "Performance Marketer",
    "퍼포먼스 마케터",
    "디지털 광고 운영",
    "광고 운영",
    "매체 운영",
    "Paid Media",
    "UA 마케터"
   ],
   "q": 17
  },
  {
   "id": "growth_marketer",
   "family": "digital_marketing",
   "ko": "그로스 마케팅",
   "en": "Growth Marketer",
   "aliases": [
    "그로스 마케팅",
    "Growth Marketer",
    "그로스 마케터",
    "그로스 해커",
    "그로스팀",
    "Growth Hacker"
   ],
   "q": 16
  },
  {
   "id": "crm_marketer",
   "family": "digital_marketing",
   "ko": "CRM 마케팅",
   "en": "CRM Marketer",
   "aliases": [
    "CRM 마케팅",
    "CRM Marketer",
    "CRM 마케터",
    "고객관계관리",
    "리텐션 마케터",
    "라이프사이클 마케팅",
    "Lifecycle Marketer"
   ],
   "q": 18
  },
  {
   "id": "content_marketer",
   "family": "digital_marketing",
   "ko": "콘텐츠 마케팅",
   "en": "Content Marketer",
   "aliases": [
    "콘텐츠 마케팅",
    "Content Marketer",
    "소셜 마케터",
    "SNS 마케터",
    "브랜디드 콘텐츠",
    "마케팅 에디터"
   ],
   "q": 17
  },
  {
   "id": "brand_marketer",
   "family": "brand",
   "ko": "브랜드 마케팅",
   "en": "Brand Marketer",
   "aliases": [
    "브랜드 마케팅",
    "Brand Marketer",
    "브랜드 마케터",
    "브랜드 매니저",
    "BM",
    "Brand Manager"
   ],
   "q": 16
  },
  {
   "id": "pr_specialist",
   "family": "brand",
   "ko": "홍보·PR",
   "en": "PR Specialist",
   "aliases": [
    "홍보·PR",
    "PR Specialist",
    "홍보",
    "PR",
    "홍보 담당자",
    "언론홍보",
    "기업홍보",
    "커뮤니케이션팀",
    "Public Relations"
   ],
   "q": 18
  },
  {
   "id": "product_marketer",
   "family": "brand",
   "ko": "프로덕트 마케팅",
   "en": "Product Marketer",
   "aliases": [
    "프로덕트 마케팅",
    "Product Marketer",
    "프로덕트 마케터",
    "제품 마케팅",
    "PMM",
    "Product Marketing Manager"
   ],
   "q": 16
  },
  {
   "id": "market_researcher",
   "family": "brand",
   "ko": "시장조사·리서치",
   "en": "Market Researcher",
   "aliases": [
    "시장조사·리서치",
    "Market Researcher",
    "시장조사",
    "마케팅 리서치",
    "리서처",
    "조사 연구원",
    "소비자 조사",
    "Research Analyst"
   ],
   "q": 16
  },
  {
   "id": "ad_planner",
   "family": "advertising",
   "ko": "광고기획",
   "en": "Advertising Planner",
   "aliases": [
    "광고기획",
    "Advertising Planner",
    "광고기획자",
    "AP",
    "어카운트 플래너",
    "캠페인 기획",
    "Account Planner"
   ],
   "q": 16
  },
  {
   "id": "account_executive",
   "family": "advertising",
   "ko": "AE",
   "en": "Account Executive",
   "aliases": [
    "AE",
    "Account Executive",
    "광고 AE",
    "어카운트 매니저",
    "광고대행사 AE",
    "Account Manager"
   ],
   "q": 16
  },
  {
   "id": "domestic_sales",
   "family": "sales",
   "ko": "국내영업",
   "en": "Domestic Sales",
   "aliases": [
    "국내영업",
    "Domestic Sales",
    "영업사원",
    "지역 영업",
    "유통 영업",
    "채널 영업",
    "루트 영업",
    "Sales Representative"
   ],
   "q": 16
  },
  {
   "id": "b2b_sales",
   "family": "sales",
   "ko": "B2B 영업",
   "en": "B2B Sales",
   "aliases": [
    "B2B 영업",
    "B2B Sales",
    "법인영업",
    "산업재 영업",
    "Corporate Sales"
   ],
   "q": 16
  },
  {
   "id": "technical_sales",
   "family": "sales",
   "ko": "기술영업",
   "en": "Technical Sales",
   "aliases": [
    "기술영업",
    "Technical Sales",
    "세일즈 엔지니어",
    "기술영업 엔지니어",
    "FAE",
    "Sales Engineer"
   ],
   "q": 16
  },
  {
   "id": "solution_sales",
   "family": "sales",
   "ko": "솔루션 영업",
   "en": "Solution Sales",
   "aliases": [
    "솔루션 영업",
    "Solution Sales",
    "IT 솔루션 영업",
    "SaaS 영업",
    "엔터프라이즈 영업",
    "Enterprise Sales"
   ],
   "q": 16
  },
  {
   "id": "auto_sales",
   "family": "sales",
   "ko": "자동차 영업",
   "en": "Automotive Sales",
   "aliases": [
    "자동차 영업",
    "Automotive Sales",
    "카마스터",
    "자동차 딜러",
    "자동차 판매",
    "세일즈 컨설턴트",
    "Car Sales",
    "Automotive Sales Consultant"
   ],
   "q": 16
  },
  {
   "id": "pharma_sales",
   "family": "sales",
   "ko": "제약영업(MR)",
   "en": "Pharmaceutical Sales Rep",
   "aliases": [
    "제약영업(MR)",
    "Pharmaceutical Sales Rep",
    "제약영업",
    "MR",
    "의약정보담당자",
    "병원 영업",
    "Medical Representative",
    "Pharmaceutical Sales"
   ],
   "q": 19
  },
  {
   "id": "sales_manager",
   "family": "sales_ops",
   "ko": "영업관리",
   "en": "Sales Operations Manager",
   "aliases": [
    "영업관리",
    "Sales Operations Manager",
    "영업지원",
    "영업기획",
    "세일즈 오퍼레이션",
    "영업관리자",
    "Sales Operations",
    "Sales Admin"
   ],
   "q": 16
  },
  {
   "id": "key_account",
   "family": "sales_ops",
   "ko": "키어카운트 관리",
   "en": "Key Account Manager",
   "aliases": [
    "키어카운트 관리",
    "Key Account Manager",
    "KAM",
    "핵심 거래처 관리",
    "대형 거래처 영업",
    "Key Account Management"
   ],
   "q": 16
  },
  {
   "id": "overseas_sales",
   "family": "trade",
   "ko": "해외영업",
   "en": "Overseas Sales",
   "aliases": [
    "해외 영업",
    "Overseas Sales",
    "해외영업팀",
    "수출영업",
    "글로벌 영업",
    "Export Sales",
    "International Sales"
   ],
   "q": 18
  },
  {
   "id": "trade_admin",
   "family": "trade",
   "ko": "무역사무",
   "en": "Trade Administrator",
   "aliases": [
    "무역사무",
    "Trade Administrator",
    "무역사무원",
    "국제무역사무원",
    "수출입 사무",
    "무역 실무",
    "수출입 담당",
    "Import/Export Coordinator"
   ],
   "q": 17
  },
  {
   "id": "global_business",
   "family": "trade",
   "ko": "글로벌 사업개발",
   "en": "Global Business Development",
   "aliases": [
    "글로벌 사업개발",
    "Global Business Development",
    "해외 사업개발",
    "해외사업",
    "글로벌 BD",
    "해외 진출",
    "International BD",
    "Overseas Business Development"
   ],
   "q": 18
  },
  {
   "id": "md",
   "family": "merchandising",
   "ko": "상품기획 MD",
   "en": "Merchandiser",
   "aliases": [
    "상품기획 MD",
    "Merchandiser",
    "MD",
    "머천다이저",
    "상품개발 MD",
    "PB 상품기획"
   ],
   "q": 16
  },
  {
   "id": "online_md",
   "family": "merchandising",
   "ko": "온라인 MD",
   "en": "E-commerce Merchandiser",
   "aliases": [
    "온라인 MD",
    "E-commerce Merchandiser",
    "이커머스 MD",
    "e커머스 MD",
    "쇼핑몰 MD",
    "플랫폼 MD",
    "카테고리 MD",
    "Online Merchandiser"
   ],
   "q": 16
  },
  {
   "id": "buyer",
   "family": "merchandising",
   "ko": "바이어",
   "en": "Buyer",
   "aliases": [
    "바이어",
    "Buyer",
    "구매 바이어",
    "유통 바이어",
    "매입 담당",
    "리테일 바이어",
    "백화점 바이어",
    "Retail Buyer"
   ],
   "q": 16
  },
  {
   "id": "fashion_md",
   "family": "merchandising",
   "ko": "패션 MD",
   "en": "Fashion Merchandiser",
   "aliases": [
    "패션 MD",
    "Fashion Merchandiser",
    "의류 MD",
    "패션 상품기획",
    "브랜드 MD",
    "리테일 MD",
    "Apparel Merchandiser"
   ],
   "q": 17
  },
  {
   "id": "purchaser",
   "family": "purchasing",
   "ko": "구매",
   "en": "Purchasing Specialist",
   "aliases": [
    "구매",
    "Purchasing Specialist",
    "구매 담당자",
    "구매팀",
    "구매관리",
    "자재구매",
    "바잉",
    "Purchasing",
    "Procurement Specialist"
   ],
   "q": 22
  },
  {
   "id": "strategic_sourcing",
   "family": "purchasing",
   "ko": "전략구매·소싱",
   "en": "Strategic Sourcing",
   "aliases": [
    "전략구매·소싱",
    "Strategic Sourcing",
    "전략구매",
    "소싱",
    "전략소싱",
    "글로벌 소싱",
    "카테고리 매니저(구매)",
    "Sourcing Manager",
    "Category Buyer"
   ],
   "q": 22
  },
  {
   "id": "public_procurement",
   "family": "purchasing",
   "ko": "조달·계약",
   "en": "Procurement & Contracts",
   "aliases": [
    "조달·계약",
    "Procurement & Contracts",
    "조달",
    "계약",
    "계약 담당",
    "공공 조달",
    "계약 관리",
    "입찰 담당",
    "Contract Administrator"
   ],
   "q": 17
  },
  {
   "id": "scm_planner",
   "family": "scm",
   "ko": "SCM",
   "en": "Supply Chain Manager",
   "aliases": [
    "SCM",
    "Supply Chain Manager",
    "SCM 기획",
    "공급망 관리",
    "수급 관리",
    "S&OP 담당",
    "Supply Chain Planner"
   ],
   "q": 21
  },
  {
   "id": "logistics_manager",
   "family": "scm",
   "ko": "물류관리",
   "en": "Logistics Manager",
   "aliases": [
    "물류관리",
    "Logistics Manager",
    "물류 담당",
    "물류기획",
    "운송 관리",
    "배송 관리",
    "국제물류",
    "Logistics Coordinator"
   ],
   "q": 22
  },
  {
   "id": "demand_planner",
   "family": "scm",
   "ko": "수요예측·수급계획",
   "en": "Demand Planner",
   "aliases": [
    "수요예측·수급계획",
    "Demand Planner",
    "수요예측",
    "수급계획",
    "수요 계획",
    "디맨드 플래너",
    "판매 계획",
    "Demand Forecasting Analyst"
   ],
   "q": 20
  },
  {
   "id": "warehouse_ops",
   "family": "scm",
   "ko": "물류센터 운영",
   "en": "Warehouse Operations",
   "aliases": [
    "물류센터 운영",
    "Warehouse Operations",
    "센터 운영",
    "창고 관리",
    "풀필먼트 운영",
    "WMS 운영",
    "Fulfillment Operations"
   ],
   "q": 22
  },
  {
   "id": "cs_agent",
   "family": "customer_support",
   "ko": "CS 상담",
   "en": "Customer Service Representative",
   "aliases": [
    "CS 상담",
    "Customer Service Representative",
    "고객상담",
    "고객센터",
    "콜센터 상담",
    "채팅 상담",
    "CS Agent"
   ],
   "q": 15
  },
  {
   "id": "cs_manager",
   "family": "customer_support",
   "ko": "CS 기획·운영",
   "en": "Customer Experience Manager",
   "aliases": [
    "CS 기획·운영",
    "Customer Experience Manager",
    "CS 기획",
    "CS 운영",
    "고객경험 기획",
    "CX 매니저",
    "VOC 담당",
    "상담센터 운영",
    "CS Operations Manager"
   ],
   "q": 16
  },
  {
   "id": "tech_support",
   "family": "customer_support",
   "ko": "기술지원",
   "en": "Technical Support Engineer",
   "aliases": [
    "기술지원",
    "Technical Support Engineer",
    "기술 지원 엔지니어",
    "테크니컬 서포트",
    "고객 기술지원",
    "헬프데스크",
    "Tech Support"
   ],
   "q": 21
  },
  {
   "id": "service_planner",
   "family": "product",
   "ko": "서비스기획",
   "en": "Service Planner",
   "aliases": [
    "서비스기획",
    "Service Planner",
    "서비스 기획자",
    "웹기획",
    "앱 기획",
    "화면 기획",
    "서비스 기획자 (PM)",
    "웹기획자",
    "앱 기획자"
   ],
   "q": 16
  },
  {
   "id": "product_manager",
   "family": "product",
   "ko": "PM(프로덕트 매니저)",
   "en": "Product Manager",
   "aliases": [
    "PM(프로덕트 매니저)",
    "Product Manager",
    "PM",
    "프로덕트 매니저",
    "제품 관리자",
    "그로스 PM"
   ],
   "q": 19
  },
  {
   "id": "product_owner",
   "family": "product",
   "ko": "PO(프로덕트 오너)",
   "en": "Product Owner",
   "aliases": [
    "PO(프로덕트 오너)",
    "Product Owner",
    "PO",
    "프로덕트 오너",
    "애자일 PO",
    "스크럼 PO"
   ],
   "q": 20
  },
  {
   "id": "project_manager_it",
   "family": "product",
   "ko": "IT 프로젝트 매니저",
   "en": "IT Project Manager",
   "aliases": [
    "IT 프로젝트 매니저",
    "IT Project Manager",
    "IT PM",
    "프로젝트 관리자",
    "SI PM",
    "PMO",
    "Project Manager"
   ],
   "q": 20
  },
  {
   "id": "frontend",
   "family": "software",
   "ko": "프론트엔드 개발자",
   "en": "Frontend Developer",
   "aliases": [
    "프론트엔드 개발자",
    "Frontend Developer",
    "프론트엔드",
    "프론트엔드 엔지니어",
    "웹 프론트엔드 개발자",
    "FE",
    "FE 개발자",
    "Frontend Engineer",
    "Front-end Developer"
   ],
   "q": 17
  },
  {
   "id": "backend",
   "family": "software",
   "ko": "백엔드 개발자",
   "en": "Backend Developer",
   "aliases": [
    "백엔드 개발자",
    "Backend Developer",
    "백엔드",
    "백엔드 엔지니어",
    "서버 개발자",
    "BE",
    "BE 개발자",
    "Backend Engineer",
    "Server Developer",
    "Back-end Developer"
   ],
   "q": 17
  },
  {
   "id": "fullstack",
   "family": "software",
   "ko": "풀스택 개발자",
   "en": "Full-stack Developer",
   "aliases": [
    "풀스택 개발자",
    "Full-stack Developer",
    "풀스택",
    "풀스택 엔지니어",
    "웹 개발자",
    "Full Stack Engineer"
   ],
   "q": 16
  },
  {
   "id": "ios",
   "family": "software",
   "ko": "iOS 개발자",
   "en": "iOS Developer",
   "aliases": [
    "iOS 개발자",
    "iOS Developer",
    "iOS",
    "iOS 엔지니어",
    "iOS 앱 개발자",
    "애플 앱 개발자",
    "Swift 개발자",
    "iOS Engineer"
   ],
   "q": 16
  },
  {
   "id": "android",
   "family": "software",
   "ko": "Android 개발자",
   "en": "Android Developer",
   "aliases": [
    "Android 개발자",
    "Android Developer",
    "Android",
    "안드로이드",
    "안드로이드 개발자",
    "Android 엔지니어",
    "안드로이드 앱 개발자",
    "AOS 개발자",
    "Android Engineer"
   ],
   "q": 16
  },
  {
   "id": "embedded_sw",
   "family": "software",
   "ko": "임베디드 개발자",
   "en": "Embedded Software Engineer",
   "aliases": [
    "임베디드 개발자",
    "Embedded Software Engineer",
    "임베디드",
    "임베디드 SW 개발자",
    "임베디드 소프트웨어 엔지니어",
    "펌웨어 개발자",
    "펌웨어 엔지니어",
    "Firmware Engineer",
    "Embedded Developer"
   ],
   "q": 23
  },
  {
   "id": "qa_engineer",
   "family": "software",
   "ko": "QA 엔지니어",
   "en": "QA Engineer",
   "aliases": [
    "QA 엔지니어",
    "QA Engineer",
    "소프트웨어 테스터",
    "테스트 엔지니어",
    "SQA",
    "SDET",
    "Software Test Engineer"
   ],
   "q": 16
  },
  {
   "id": "sw_architect",
   "family": "software",
   "ko": "솔루션 아키텍트",
   "en": "Solutions Architect",
   "aliases": [
    "솔루션 아키텍트",
    "Solutions Architect",
    "소프트웨어 아키텍트",
    "시스템 아키텍트",
    "SA",
    "Solution Architect",
    "Software Architect"
   ],
   "q": 16
  },
  {
   "id": "data_analyst",
   "family": "data",
   "ko": "데이터 분석가",
   "en": "Data Analyst",
   "aliases": [
    "데이터 분석가",
    "Data Analyst",
    "데이터 애널리스트",
    "DA",
    "프로덕트 분석가",
    "비즈니스 분석가",
    "Product Analyst",
    "데이터 애널"
   ],
   "q": 17
  },
  {
   "id": "bi_analyst",
   "family": "data",
   "ko": "BI 분석가",
   "en": "BI Analyst",
   "aliases": [
    "BI 분석가",
    "BI Analyst",
    "BI 애널리스트",
    "BI 담당자",
    "BI 개발자",
    "Business Intelligence Analyst",
    "Reporting Analyst"
   ],
   "q": 16
  },
  {
   "id": "data_scientist",
   "family": "data",
   "ko": "데이터 사이언티스트",
   "en": "Data Scientist",
   "aliases": [
    "데이터 사이언티스트",
    "Data Scientist",
    "데이터 과학자",
    "DS",
    "Applied Scientist"
   ],
   "q": 16
  },
  {
   "id": "data_engineer",
   "family": "ai",
   "ko": "데이터 엔지니어",
   "en": "Data Engineer",
   "aliases": [
    "데이터 엔지니어",
    "Data Engineer",
    "데이터",
    "DE",
    "데이터 플랫폼 엔지니어",
    "빅데이터 엔지니어",
    "Data Platform Engineer"
   ],
   "q": 16
  },
  {
   "id": "ml_engineer",
   "family": "ai",
   "ko": "ML 엔지니어",
   "en": "Machine Learning Engineer",
   "aliases": [
    "ML 엔지니어",
    "Machine Learning Engineer",
    "ML",
    "머신러닝 엔지니어",
    "MLE",
    "MLOps 엔지니어",
    "ML Engineer"
   ],
   "q": 16
  },
  {
   "id": "ai_engineer",
   "family": "ai",
   "ko": "AI 엔지니어",
   "en": "AI Engineer",
   "aliases": [
    "AI 엔지니어",
    "AI Engineer",
    "AI",
    "AI 개발자",
    "LLM 엔지니어",
    "AI 애플리케이션 엔지니어",
    "LLM Engineer",
    "Applied AI Engineer",
    "인공지능 엔지니어"
   ],
   "q": 16
  },
  {
   "id": "ai_researcher",
   "family": "ai",
   "ko": "AI 연구원",
   "en": "AI Research Scientist",
   "aliases": [
    "AI 연구원",
    "AI Research Scientist",
    "AI 리서처",
    "머신러닝 연구원",
    "딥러닝 연구원",
    "리서치 사이언티스트",
    "ML Researcher"
   ],
   "q": 16
  },
  {
   "id": "ai_pm",
   "family": "ai",
   "ko": "AI PM",
   "en": "AI Product Manager",
   "aliases": [
    "AI PM",
    "AI Product Manager",
    "AI 프로덕트 매니저",
    "AI 기획자",
    "AI 서비스 기획자",
    "AI PO",
    "AI Product Owner"
   ],
   "q": 16
  },
  {
   "id": "devops",
   "family": "infra",
   "ko": "DevOps 엔지니어",
   "en": "DevOps Engineer",
   "aliases": [
    "DevOps 엔지니어",
    "DevOps Engineer",
    "DevOps",
    "데브옵스",
    "데브옵스 엔지니어",
    "플랫폼 엔지니어",
    "배포 엔지니어",
    "CI/CD 엔지니어"
   ],
   "q": 17
  },
  {
   "id": "sre",
   "family": "infra",
   "ko": "SRE",
   "en": "Site Reliability Engineer",
   "aliases": [
    "SRE",
    "Site Reliability Engineer",
    "사이트 신뢰성 엔지니어",
    "서비스 운영 엔지니어",
    "프로덕션 엔지니어"
   ],
   "q": 17
  },
  {
   "id": "cloud_engineer",
   "family": "infra",
   "ko": "클라우드 엔지니어",
   "en": "Cloud Engineer",
   "aliases": [
    "클라우드 엔지니어",
    "Cloud Engineer",
    "클라우드",
    "클라우드 아키텍트",
    "AWS 엔지니어",
    "클라우드 인프라 엔지니어",
    "MSP 엔지니어",
    "클라우드 운영"
   ],
   "q": 15
  },
  {
   "id": "system_engineer",
   "family": "infra",
   "ko": "시스템 엔지니어",
   "en": "Systems Engineer",
   "aliases": [
    "시스템 엔지니어",
    "Systems Engineer",
    "시스템",
    "System Engineer",
    "시스템 관리자",
    "리눅스 엔지니어",
    "전산 담당",
    "SE"
   ],
   "q": 17
  },
  {
   "id": "network_engineer",
   "family": "infra",
   "ko": "네트워크 엔지니어",
   "en": "Network Engineer",
   "aliases": [
    "네트워크 엔지니어",
    "Network Engineer",
    "네트워크",
    "네트워크 관리자",
    "망 관리",
    "NE",
    "네트워크 운영"
   ],
   "q": 17
  },
  {
   "id": "dba",
   "family": "infra",
   "ko": "DBA",
   "en": "Database Administrator",
   "aliases": [
    "DBA",
    "Database Administrator",
    "데이터베이스 관리자",
    "DB 엔지니어",
    "데이터베이스 엔지니어",
    "DB 운영"
   ],
   "q": 17
  },
  {
   "id": "security_engineer",
   "family": "security",
   "ko": "보안 엔지니어",
   "en": "Security Engineer",
   "aliases": [
    "보안 엔지니어",
    "Security Engineer",
    "보안",
    "정보보안 엔지니어",
    "보안 담당자",
    "정보보호 담당",
    "보안 솔루션 엔지니어",
    "모의해킹"
   ],
   "q": 17
  },
  {
   "id": "security_analyst",
   "family": "security",
   "ko": "보안관제·침해대응",
   "en": "Security Operations Analyst",
   "aliases": [
    "보안관제·침해대응",
    "Security Operations Analyst",
    "보안관제",
    "침해대응",
    "보안관제 요원",
    "SOC 분석가",
    "Security Analyst",
    "CERT",
    "관제 엔지니어"
   ],
   "q": 17
  },
  {
   "id": "game_client",
   "family": "game",
   "ko": "게임 클라이언트 개발자",
   "en": "Game Client Programmer",
   "aliases": [
    "게임 클라이언트 개발자",
    "Game Client Programmer",
    "게임 클라이언트",
    "클라이언트 프로그래머",
    "유니티 개발자",
    "언리얼 개발자",
    "게임 프로그래머",
    "콘텐츠 프로그래머"
   ],
   "q": 17
  },
  {
   "id": "game_server",
   "family": "game",
   "ko": "게임 서버 개발자",
   "en": "Game Server Programmer",
   "aliases": [
    "게임 서버 개발자",
    "Game Server Programmer",
    "게임 서버",
    "게임 서버 프로그래머",
    "온라인 게임 서버",
    "라이브 서버 개발",
    "백엔드(게임)"
   ],
   "q": 16
  },
  {
   "id": "game_designer",
   "family": "game_business",
   "ko": "게임기획",
   "en": "Game Designer",
   "aliases": [
    "게임 기획",
    "Game Designer",
    "게임기획자",
    "시스템 기획",
    "콘텐츠 기획(게임)",
    "레벨 디자이너",
    "밸런스 기획",
    "전투 기획"
   ],
   "q": 16
  },
  {
   "id": "game_ops",
   "family": "game_business",
   "ko": "게임 운영·사업PM",
   "en": "Game Operations / Live PM",
   "aliases": [
    "게임 운영·사업PM",
    "Game Operations / Live PM",
    "게임 운영",
    "사업PM",
    "게임 사업PM",
    "Live Ops",
    "게임 운영 PM",
    "라이브 서비스 PM",
    "게임 사업",
    "퍼블리싱 PM"
   ],
   "q": 16
  },
  {
   "id": "ux_designer",
   "family": "digital_design",
   "ko": "UX 디자이너",
   "en": "UX Designer",
   "aliases": [
    "UX 디자이너",
    "UX Designer",
    "사용자 경험 디자이너",
    "UX 리서처",
    "UI/UX 디자이너",
    "UXUI 디자이너"
   ],
   "q": 17
  },
  {
   "id": "ui_designer",
   "family": "digital_design",
   "ko": "UI 디자이너",
   "en": "UI Designer",
   "aliases": [
    "UI 디자이너",
    "UI Designer",
    "GUI 디자이너",
    "인터페이스 디자이너",
    "앱 디자이너",
    "웹 디자이너",
    "비주얼 디자이너(디지털)"
   ],
   "q": 17
  },
  {
   "id": "product_designer",
   "family": "digital_design",
   "ko": "프로덕트 디자이너",
   "en": "Product Designer",
   "aliases": [
    "프로덕트 디자이너",
    "Product Designer",
    "PD(디자인)",
    "제품 디자이너(디지털)"
   ],
   "q": 17
  },
  {
   "id": "graphic_designer",
   "family": "visual_design",
   "ko": "그래픽·BX 디자이너",
   "en": "Graphic / Brand Designer",
   "aliases": [
    "그래픽·BX 디자이너",
    "Graphic / Brand Designer",
    "그래픽",
    "BX 디자이너",
    "그래픽 디자이너",
    "브랜드 디자이너",
    "Graphic Designer",
    "Brand Designer",
    "편집 디자이너",
    "시각 디자이너",
    "패키지 디자이너"
   ],
   "q": 17
  },
  {
   "id": "industrial_designer",
   "family": "visual_design",
   "ko": "제품(산업) 디자이너",
   "en": "Industrial Designer",
   "aliases": [
    "제품(산업) 디자이너",
    "Industrial Designer",
    "제품 디자이너",
    "산업",
    "산업 디자이너",
    "ID 디자이너",
    "프로덕트 디자이너(하드웨어)",
    "CMF 디자이너"
   ],
   "q": 17
  },
  {
   "id": "interior_designer",
   "family": "visual_design",
   "ko": "인테리어 디자이너",
   "en": "Interior Designer",
   "aliases": [
    "인테리어 디자이너",
    "Interior Designer",
    "실내건축 디자이너",
    "공간 디자이너",
    "공간 디자인",
    "인테리어 설계",
    "VMD(공간)"
   ],
   "q": 17
  },
  {
   "id": "fashion_designer",
   "family": "visual_design",
   "ko": "패션 디자이너",
   "en": "Fashion Designer",
   "aliases": [
    "패션 디자이너",
    "Fashion Designer",
    "의류 디자이너",
    "브랜드 디자이너(패션)",
    "디자인실",
    "잡화 디자이너",
    "니트 디자이너"
   ],
   "q": 17
  },
  {
   "id": "content_planner",
   "family": "content",
   "ko": "콘텐츠 기획",
   "en": "Content Planner",
   "aliases": [
    "콘텐츠 기획",
    "Content Planner",
    "콘텐츠 기획자",
    "콘텐츠 에디터",
    "채널 운영",
    "브랜디드 콘텐츠 기획"
   ],
   "q": 17
  },
  {
   "id": "editor",
   "family": "content",
   "ko": "출판 편집자",
   "en": "Editor",
   "aliases": [
    "출판 편집자",
    "Editor",
    "도서 편집자",
    "기획 편집자",
    "책 편집",
    "출판 기획"
   ],
   "q": 17
  },
  {
   "id": "copywriter",
   "family": "content",
   "ko": "카피라이터",
   "en": "Copywriter",
   "aliases": [
    "카피라이터",
    "Copywriter",
    "광고 카피라이터",
    "CW",
    "크리에이티브",
    "브랜드 카피라이터"
   ],
   "q": 17
  },
  {
   "id": "journalist",
   "family": "content",
   "ko": "기자",
   "en": "Journalist / Reporter",
   "aliases": [
    "기자",
    "Journalist / Reporter",
    "취재기자",
    "Journalist",
    "Reporter",
    "방송기자",
    "신문기자",
    "온라인 기자",
    "에디터(언론)"
   ],
   "q": 18
  },
  {
   "id": "broadcast_pd",
   "family": "broadcast",
   "ko": "방송 PD",
   "en": "Broadcast Producer",
   "aliases": [
    "방송PD",
    "Broadcast Producer",
    "PD",
    "연출",
    "방송 연출가",
    "예능 PD",
    "교양 PD",
    "조연출",
    "AD",
    "TV Producer"
   ],
   "q": 18
  },
  {
   "id": "video_producer",
   "family": "broadcast",
   "ko": "영상 PD·영상 제작",
   "en": "Video Producer",
   "aliases": [
    "영상 PD·영상 제작",
    "Video Producer",
    "영상PD",
    "영상 제작",
    "영상 제작자",
    "콘텐츠 PD",
    "브랜디드 콘텐츠 PD",
    "유튜브 PD",
    "영상 크리에이터",
    "Content Producer"
   ],
   "q": 17
  },
  {
   "id": "video_editor",
   "family": "broadcast",
   "ko": "영상 편집자",
   "en": "Video Editor",
   "aliases": [
    "영상편집자",
    "Video Editor",
    "편집 PD",
    "편집기사",
    "방송편집기사",
    "유튜브 편집자",
    "Post-production Editor"
   ],
   "q": 17
  },
  {
   "id": "broadcast_writer",
   "family": "broadcast",
   "ko": "방송작가",
   "en": "Broadcast Writer",
   "aliases": [
    "방송 작가",
    "Broadcast Writer",
    "구성작가",
    "예능작가",
    "교양작가",
    "막내작가",
    "서브작가",
    "메인작가",
    "라디오 작가",
    "Scriptwriter"
   ],
   "q": 17
  },
  {
   "id": "announcer",
   "family": "broadcast",
   "ko": "아나운서",
   "en": "Announcer",
   "aliases": [
    "아나운서",
    "Announcer",
    "앵커",
    "MC",
    "진행자",
    "캐스터",
    "리포터",
    "쇼호스트",
    "News Anchor",
    "Presenter"
   ],
   "q": 17
  },
  {
   "id": "rnd_planner",
   "family": "rnd",
   "ko": "연구기획·관리",
   "en": "R&D Planner",
   "aliases": [
    "연구기획·관리",
    "R&D Planner",
    "연구기획",
    "R&D 기획",
    "기술기획",
    "R&D PM",
    "Technology Planning"
   ],
   "q": 17
  },
  {
   "id": "product_developer",
   "family": "rnd",
   "ko": "제품개발 엔지니어",
   "en": "Product Development Engineer",
   "aliases": [
    "제품개발 엔지니어",
    "Product Development Engineer",
    "제품개발자",
    "개발 엔지니어",
    "NPD 엔지니어",
    "제품 설계 엔지니어"
   ],
   "q": 17
  },
  {
   "id": "control_engineer",
   "family": "rnd",
   "ko": "제어 엔지니어",
   "en": "Control Engineer",
   "aliases": [
    "제어 엔지니어",
    "Control Engineer",
    "제어",
    "제어설계",
    "자동제어",
    "PLC 엔지니어",
    "제어 시스템 엔지니어",
    "Controls Engineer",
    "Automation Engineer"
   ],
   "q": 17
  },
  {
   "id": "semi_process",
   "family": "semiconductor",
   "ko": "반도체 공정 엔지니어",
   "en": "Semiconductor Process Engineer",
   "aliases": [
    "반도체 공정 엔지니어",
    "Semiconductor Process Engineer",
    "반도체 공정",
    "양산기술",
    "단위공정 엔지니어",
    "포토 엔지니어",
    "식각 엔지니어",
    "박막 엔지니어",
    "공정 엔지니어(반도체)",
    "Fab 공정 엔지니어"
   ],
   "q": 18
  },
  {
   "id": "semi_equipment",
   "family": "semiconductor",
   "ko": "반도체 설비 엔지니어",
   "en": "Semiconductor Equipment Engineer",
   "aliases": [
    "반도체 설비 엔지니어",
    "Semiconductor Equipment Engineer",
    "반도체 설비",
    "설비기술",
    "장비 엔지니어",
    "장비기술",
    "양산 설비"
   ],
   "q": 18
  },
  {
   "id": "semi_design",
   "family": "semiconductor",
   "ko": "반도체 회로설계",
   "en": "Semiconductor Circuit Designer",
   "aliases": [
    "반도체 회로설계",
    "Semiconductor Circuit Designer",
    "회로설계",
    "반도체 설계",
    "아날로그 설계",
    "디지털 설계",
    "레이아웃",
    "설계 검증",
    "Circuit Designer",
    "IC Design Engineer",
    "ASIC Engineer"
   ],
   "q": 17
  },
  {
   "id": "semi_yield",
   "family": "semiconductor",
   "ko": "수율·불량분석 엔지니어",
   "en": "Yield / Failure Analysis Engineer",
   "aliases": [
    "수율·불량분석 엔지니어",
    "Yield / Failure Analysis Engineer",
    "수율",
    "불량분석 엔지니어",
    "수율·불량분석",
    "수율 엔지니어",
    "불량분석",
    "FA 엔지니어",
    "품질 분석",
    "Yield Engineer",
    "Failure Analysis Engineer"
   ],
   "q": 17
  },
  {
   "id": "hw_engineer",
   "family": "electronics",
   "ko": "하드웨어(전자회로) 개발",
   "en": "Hardware Engineer",
   "aliases": [
    "하드웨어(전자회로) 개발",
    "Hardware Engineer",
    "하드웨어 개발",
    "전자회로",
    "HW 개발자",
    "회로 개발",
    "전자회로 설계",
    "보드 설계",
    "PCB 설계",
    "Electronics Engineer"
   ],
   "q": 17
  },
  {
   "id": "electrical_engineer",
   "family": "electronics",
   "ko": "전기설계",
   "en": "Electrical Design Engineer",
   "aliases": [
    "전기설계",
    "Electrical Design Engineer",
    "전기 엔지니어",
    "전기 설계 엔지니어",
    "수배전 설계",
    "플랜트 전기",
    "Electrical Engineer"
   ],
   "q": 17
  },
  {
   "id": "display_engineer",
   "family": "electronics",
   "ko": "디스플레이 엔지니어",
   "en": "Display Engineer",
   "aliases": [
    "디스플레이 엔지니어",
    "Display Engineer",
    "디스플레이",
    "디스플레이 공정",
    "패널 개발",
    "OLED 엔지니어",
    "디스플레이 회로",
    "Panel Engineer"
   ],
   "q": 17
  },
  {
   "id": "mechanical_designer",
   "family": "mechanical",
   "ko": "기계설계",
   "en": "Mechanical Design Engineer",
   "aliases": [
    "기계설계",
    "Mechanical Design Engineer",
    "기구설계",
    "설계 엔지니어",
    "기계 엔지니어",
    "기구 엔지니어",
    "Mechanical Engineer"
   ],
   "q": 17
  },
  {
   "id": "automotive_engineer",
   "family": "mechanical",
   "ko": "자동차 연구개발",
   "en": "Automotive R&D Engineer",
   "aliases": [
    "자동차 연구개발",
    "Automotive R&D Engineer",
    "자동차 연구원",
    "차량 개발",
    "차량 설계",
    "차량 시험",
    "완성차 R&D",
    "자동차 엔지니어",
    "Automotive Engineer",
    "Vehicle Engineer"
   ],
   "q": 17
  },
  {
   "id": "cae_engineer",
   "family": "mechanical",
   "ko": "해석(CAE) 엔지니어",
   "en": "CAE Engineer",
   "aliases": [
    "해석(CAE) 엔지니어",
    "CAE Engineer",
    "해석 엔지니어",
    "CAE",
    "해석",
    "구조해석",
    "열유동 해석",
    "시뮬레이션 엔지니어",
    "Simulation Engineer",
    "FEA Engineer"
   ],
   "q": 17
  },
  {
   "id": "robotics_engineer",
   "family": "mechanical",
   "ko": "로봇·메카트로닉스",
   "en": "Robotics Engineer",
   "aliases": [
    "로봇·메카트로닉스",
    "Robotics Engineer",
    "로봇",
    "메카트로닉스",
    "로봇 엔지니어",
    "로봇 개발",
    "로봇 제어",
    "Mechatronics Engineer"
   ],
   "q": 17
  },
  {
   "id": "chemical_process",
   "family": "chemical",
   "ko": "화공 공정엔지니어",
   "en": "Chemical Process Engineer",
   "aliases": [
    "화공 공정엔지니어",
    "Chemical Process Engineer",
    "화공 공정",
    "화공 엔지니어",
    "화학공정",
    "플랜트 공정",
    "생산기술(화학)"
   ],
   "q": 18
  },
  {
   "id": "materials_researcher",
   "family": "chemical",
   "ko": "소재 연구원",
   "en": "Materials Researcher",
   "aliases": [
    "소재 연구원",
    "Materials Researcher",
    "소재 개발",
    "재료 연구원",
    "신소재 연구",
    "고분자 연구원",
    "Materials Scientist"
   ],
   "q": 17
  },
  {
   "id": "chemical_researcher",
   "family": "chemical",
   "ko": "화학 연구원(합성·분석)",
   "en": "Chemical Researcher",
   "aliases": [
    "화학 연구원(합성·분석)",
    "Chemical Researcher",
    "화학 연구원",
    "합성",
    "합성 연구원",
    "유기합성",
    "분석화학",
    "Synthetic Chemist",
    "Analytical Chemist"
   ],
   "q": 17
  },
  {
   "id": "battery_engineer",
   "family": "chemical",
   "ko": "2차전지 엔지니어",
   "en": "Battery Engineer",
   "aliases": [
    "2차전지 엔지니어",
    "Battery Engineer",
    "2차전지",
    "배터리 엔지니어",
    "배터리 연구원",
    "셀 개발",
    "전지 공정",
    "전극 공정",
    "Cell Engineer"
   ],
   "q": 17
  },
  {
   "id": "bio_researcher",
   "family": "bio_pharma",
   "ko": "바이오 연구원",
   "en": "Bio Researcher",
   "aliases": [
    "바이오 연구원",
    "Bio Researcher",
    "생명과학 연구원",
    "바이오 R&D",
    "세포배양 연구원",
    "분자생물학 연구원",
    "Life Science Researcher"
   ],
   "q": 18
  },
  {
   "id": "pharma_researcher",
   "family": "bio_pharma",
   "ko": "제약 연구원(신약개발)",
   "en": "Pharmaceutical Researcher",
   "aliases": [
    "제약 연구원(신약개발)",
    "Pharmaceutical Researcher",
    "제약 연구원",
    "신약개발",
    "신약개발 연구원",
    "제제 연구원",
    "의약품 연구개발",
    "Formulation Scientist",
    "Drug Discovery Scientist"
   ],
   "q": 17
  },
  {
   "id": "pharma_qa",
   "family": "bio_pharma",
   "ko": "제약 QA·QC(GMP)",
   "en": "Pharma QA/QC",
   "aliases": [
    "제약 QA·QC(GMP)",
    "Pharma QA/QC",
    "제약 QA·QC",
    "GMP",
    "제약 QA",
    "제약 QC",
    "GMP 담당",
    "밸리데이션 담당",
    "Pharma QA"
   ],
   "q": 18
  },
  {
   "id": "cra",
   "family": "bio_pharma",
   "ko": "임상연구(CRA)",
   "en": "Clinical Research Associate",
   "aliases": [
    "임상연구(CRA)",
    "Clinical Research Associate",
    "임상연구",
    "CRA",
    "임상연구 담당자",
    "임상시험 모니터요원",
    "임상 모니터",
    "Clinical Monitor"
   ],
   "q": 17
  },
  {
   "id": "regulatory_affairs",
   "family": "bio_pharma",
   "ko": "인허가(RA)",
   "en": "Regulatory Affairs",
   "aliases": [
    "인허가(RA)",
    "Regulatory Affairs",
    "인허가",
    "인허가 담당",
    "허가 담당",
    "약사 업무",
    "규제 대응",
    "Regulatory Specialist"
   ],
   "q": 17
  },
  {
   "id": "env_engineer",
   "family": "environment",
   "ko": "환경 엔지니어",
   "en": "Environmental Engineer",
   "aliases": [
    "환경 엔지니어",
    "Environmental Engineer",
    "환경 담당자",
    "환경관리 담당",
    "수처리 엔지니어",
    "대기 엔지니어",
    "EHS 환경"
   ],
   "q": 18
  },
  {
   "id": "env_consultant",
   "family": "environment",
   "ko": "환경영향평가·컨설팅",
   "en": "Environmental Consultant",
   "aliases": [
    "환경영향평가·컨설팅",
    "Environmental Consultant",
    "환경영향평가",
    "컨설팅",
    "환경 컨설턴트",
    "환경평가 담당",
    "환경 조사",
    "EIA Specialist"
   ],
   "q": 17
  },
  {
   "id": "esg_manager",
   "family": "environment",
   "ko": "ESG 담당",
   "en": "ESG Manager",
   "aliases": [
    "ESG 담당",
    "ESG Manager",
    "ESG",
    "지속가능경영 담당",
    "ESG 매니저",
    "탄소중립 담당",
    "Sustainability Manager"
   ],
   "q": 17
  },
  {
   "id": "power_plant_ops",
   "family": "energy",
   "ko": "발전설비 운영",
   "en": "Power Plant Operations Engineer",
   "aliases": [
    "발전설비 운영",
    "Power Plant Operations Engineer",
    "발전 운전원",
    "발전소 운전",
    "발전 정비",
    "Power Plant Operator",
    "Plant Operations Engineer"
   ],
   "q": 17
  },
  {
   "id": "renewable_energy",
   "family": "energy",
   "ko": "신재생에너지",
   "en": "Renewable Energy Engineer",
   "aliases": [
    "신재생에너지",
    "Renewable Energy Engineer",
    "신재생에너지 엔지니어",
    "태양광 엔지니어",
    "풍력 엔지니어",
    "재생에너지 사업개발",
    "Solar Engineer"
   ],
   "q": 17
  },
  {
   "id": "power_grid",
   "family": "energy",
   "ko": "전력계통",
   "en": "Power Systems Engineer",
   "aliases": [
    "전력계통",
    "Power Systems Engineer",
    "전력계통 엔지니어",
    "계통 운영",
    "Grid Operator"
   ],
   "q": 17
  },
  {
   "id": "architect",
   "family": "architecture",
   "ko": "건축설계",
   "en": "Architectural Designer",
   "aliases": [
    "건축설계",
    "Architectural Designer",
    "건축 디자이너",
    "설계사무소",
    "건축가",
    "Architect"
   ],
   "q": 18
  },
  {
   "id": "building_construction",
   "family": "architecture",
   "ko": "건축시공·현장관리",
   "en": "Construction Site Manager",
   "aliases": [
    "건축시공·현장관리",
    "Construction Site Manager",
    "건축시공",
    "현장관리",
    "현장 기사",
    "시공관리",
    "공사 담당",
    "Site Engineer"
   ],
   "q": 18
  },
  {
   "id": "building_services",
   "family": "architecture",
   "ko": "건축설비(MEP)",
   "en": "MEP Engineer",
   "aliases": [
    "건축설비(MEP)",
    "MEP Engineer",
    "건축설비",
    "MEP",
    "기계설비",
    "전기설비",
    "HVAC Engineer"
   ],
   "q": 17
  },
  {
   "id": "cost_estimator",
   "family": "architecture",
   "ko": "적산·공무",
   "en": "Cost Estimator / Project Controls",
   "aliases": [
    "적산·공무",
    "Cost Estimator / Project Controls",
    "적산",
    "견적",
    "현장 공무",
    "Cost Estimator",
    "Project Controls"
   ],
   "q": 17
  },
  {
   "id": "civil_designer",
   "family": "civil",
   "ko": "토목설계",
   "en": "Civil Design Engineer",
   "aliases": [
    "토목설계",
    "Civil Design Engineer",
    "토목 엔지니어",
    "도로설계",
    "교량설계"
   ],
   "q": 17
  },
  {
   "id": "civil_construction",
   "family": "civil",
   "ko": "토목시공",
   "en": "Civil Construction Engineer",
   "aliases": [
    "토목시공",
    "Civil Construction Engineer",
    "토목 현장 기사",
    "토목 공사 관리",
    "Site Engineer (Civil)"
   ],
   "q": 17
  },
  {
   "id": "structural_engineer",
   "family": "civil",
   "ko": "구조 엔지니어",
   "en": "Structural Engineer",
   "aliases": [
    "구조 엔지니어",
    "Structural Engineer",
    "구조",
    "구조설계",
    "구조기술자"
   ],
   "q": 17
  },
  {
   "id": "landscape_architect",
   "family": "landscape",
   "ko": "조경설계·시공",
   "en": "Landscape Architect",
   "aliases": [
    "조경설계·시공",
    "Landscape Architect",
    "조경설계",
    "시공",
    "조경시공",
    "조경 엔지니어",
    "조경기사",
    "Landscape Designer"
   ],
   "q": 17
  },
  {
   "id": "safety_manager",
   "family": "safety",
   "ko": "안전관리자",
   "en": "Safety Manager",
   "aliases": [
    "안전관리자",
    "Safety Manager",
    "산업안전",
    "EHS 안전",
    "안전팀",
    "HSE Manager"
   ],
   "q": 18
  },
  {
   "id": "health_manager",
   "family": "safety",
   "ko": "보건관리자",
   "en": "Occupational Health Manager",
   "aliases": [
    "보건관리자",
    "Occupational Health Manager",
    "산업보건",
    "산업간호",
    "사내 보건",
    "Industrial Health Nurse"
   ],
   "q": 17
  },
  {
   "id": "construction_safety",
   "family": "safety",
   "ko": "건설 안전관리",
   "en": "Construction Safety Manager",
   "aliases": [
    "건설 안전관리",
    "Construction Safety Manager",
    "건설 안전관리자",
    "현장 안전관리",
    "건설안전"
   ],
   "q": 18
  },
  {
   "id": "fire_safety",
   "family": "safety",
   "ko": "소방안전관리",
   "en": "Fire Safety Manager",
   "aliases": [
    "소방안전관리",
    "Fire Safety Manager",
    "소방안전관리자",
    "소방 담당",
    "방재 담당",
    "시설 소방"
   ],
   "q": 17
  },
  {
   "id": "production_manager",
   "family": "production",
   "ko": "생산관리",
   "en": "Production Manager",
   "aliases": [
    "생산관리",
    "Production Manager",
    "생산관리자",
    "생산계획",
    "생산관리 담당자",
    "생산관리팀",
    "PM(생산)",
    "Production Planning",
    "Production Control",
    "생산운영"
   ],
   "q": 18
  },
  {
   "id": "production_engineer",
   "family": "production",
   "ko": "생산기술",
   "en": "Production Engineer",
   "aliases": [
    "생산기술",
    "Production Engineer",
    "생산기술 엔지니어",
    "생기",
    "생산기술팀",
    "제조기술",
    "Manufacturing Engineer",
    "Production Engineering"
   ],
   "q": 17
  },
  {
   "id": "maintenance_engineer",
   "family": "production",
   "ko": "설비보전",
   "en": "Maintenance Engineer",
   "aliases": [
    "설비보전",
    "Maintenance Engineer",
    "설비보전 엔지니어",
    "보전",
    "메인트",
    "설비관리",
    "Maintenance",
    "설비 유지보수"
   ],
   "q": 19
  },
  {
   "id": "shop_floor_supervisor",
   "family": "production",
   "ko": "제조 현장관리",
   "en": "Shop Floor Supervisor",
   "aliases": [
    "제조 현장관리",
    "Shop Floor Supervisor",
    "생산 감독자",
    "조장",
    "반장",
    "직장",
    "라인 리더",
    "Production Supervisor",
    "현장 감독"
   ],
   "q": 17
  },
  {
   "id": "quality_control",
   "family": "quality",
   "ko": "품질관리(QC)",
   "en": "Quality Control",
   "aliases": [
    "품질관리(QC)",
    "Quality Control",
    "품질검사",
    "검사원",
    "품질관리 엔지니어",
    "QC 엔지니어",
    "공정품질"
   ],
   "q": 17
  },
  {
   "id": "quality_assurance",
   "family": "quality",
   "ko": "품질보증(QA)",
   "en": "Quality Assurance",
   "aliases": [
    "품질보증(QA)",
    "Quality Assurance",
    "품질경영",
    "고객품질",
    "품질시스템"
   ],
   "q": 17
  },
  {
   "id": "supplier_quality",
   "family": "quality",
   "ko": "협력사 품질(SQ)",
   "en": "Supplier Quality Engineer",
   "aliases": [
    "협력사 품질(SQ)",
    "Supplier Quality Engineer",
    "협력사 품질",
    "SQ",
    "SQE",
    "협력사 품질관리",
    "구매품질",
    "외주품질",
    "Supplier Quality",
    "부품 품질"
   ],
   "q": 17
  },
  {
   "id": "reliability_engineer",
   "family": "quality",
   "ko": "신뢰성 엔지니어",
   "en": "Reliability Engineer",
   "aliases": [
    "신뢰성 엔지니어",
    "Reliability Engineer",
    "신뢰성",
    "신뢰성 시험",
    "신뢰성 평가",
    "Reliability",
    "수명 평가",
    "RE"
   ],
   "q": 17
  },
  {
   "id": "process_engineer",
   "family": "process",
   "ko": "공정기술",
   "en": "Process Engineer",
   "aliases": [
    "공정기술",
    "Process Engineer",
    "공정기술 엔지니어",
    "공정개발",
    "공정관리",
    "PE"
   ],
   "q": 17
  },
  {
   "id": "process_innovation",
   "family": "process",
   "ko": "공정혁신·6시그마",
   "en": "Process Improvement / Six Sigma",
   "aliases": [
    "공정혁신·6시그마",
    "Process Improvement / Six Sigma",
    "공정혁신",
    "6시그마",
    "식스시그마",
    "혁신 담당",
    "경영혁신",
    "린 생산",
    "Continuous Improvement",
    "Six Sigma",
    "BB",
    "GB",
    "개선 활동"
   ],
   "q": 17
  },
  {
   "id": "industrial_engineer",
   "family": "process",
   "ko": "IE(산업공학)",
   "en": "Industrial Engineer",
   "aliases": [
    "IE(산업공학)",
    "Industrial Engineer",
    "IE",
    "산업공학",
    "IE 엔지니어",
    "생산성 분석",
    "표준시간",
    "Industrial Engineering",
    "IE 담당"
   ],
   "q": 17
  },
  {
   "id": "research_scientist",
   "family": "science",
   "ko": "연구원(기초·응용과학)",
   "en": "Research Scientist",
   "aliases": [
    "연구원(기초·응용과학)",
    "Research Scientist",
    "기초",
    "응용과학",
    "연구직",
    "기초연구",
    "응용연구",
    "Researcher",
    "R&D 연구원",
    "과학자"
   ],
   "q": 17
  },
  {
   "id": "lab_analyst",
   "family": "science",
   "ko": "분석 연구원",
   "en": "Laboratory Analyst",
   "aliases": [
    "Laboratory Analyst",
    "분석직",
    "시험 분석",
    "기기분석",
    "Lab Analyst",
    "Analytical Scientist",
    "분석 담당",
    "QC 분석"
   ],
   "q": 18
  },
  {
   "id": "statistician",
   "family": "science",
   "ko": "통계 분석 연구원",
   "en": "Statistician",
   "aliases": [
    "통계 분석 연구원",
    "Statistician",
    "통계연구원",
    "통계 분석가",
    "통계학 연구원",
    "Biostatistician",
    "통계 담당",
    "통계 컨설팅"
   ],
   "q": 17
  },
  {
   "id": "elementary_teacher",
   "family": "school",
   "ko": "초등교사",
   "en": "Elementary School Teacher",
   "aliases": [
    "초등 교사",
    "Elementary School Teacher",
    "초등학교 교사",
    "초등 담임",
    "교대",
    "Elementary Teacher",
    "Primary School Teacher",
    "초등 임용"
   ],
   "q": 18
  },
  {
   "id": "secondary_teacher",
   "family": "school",
   "ko": "중등교사",
   "en": "Secondary School Teacher",
   "aliases": [
    "중등교사",
    "Secondary School Teacher",
    "중학교 교사",
    "고등학교 교사",
    "교과 교사",
    "중등 임용",
    "Secondary Teacher",
    "High School Teacher",
    "Middle School Teacher",
    "담임교사"
   ],
   "q": 17
  },
  {
   "id": "special_ed_teacher",
   "family": "school",
   "ko": "특수교사",
   "en": "Special Education Teacher",
   "aliases": [
    "특수교사",
    "Special Education Teacher",
    "특수교육 교사",
    "특수학급 교사",
    "특수학교 교사",
    "특수 임용",
    "통합교육 교사"
   ],
   "q": 18
  },
  {
   "id": "early_childhood_teacher",
   "family": "school",
   "ko": "유치원·보육교사",
   "en": "Early Childhood Teacher",
   "aliases": [
    "유치원·보육교사",
    "Early Childhood Teacher",
    "유치원",
    "보육교사",
    "유치원 교사",
    "유아교사",
    "어린이집 교사",
    "Kindergarten Teacher",
    "유아 임용"
   ],
   "q": 17
  },
  {
   "id": "academy_instructor",
   "family": "edu_business",
   "ko": "학원 강사",
   "en": "Academy Instructor",
   "aliases": [
    "학원강사",
    "Academy Instructor",
    "입시 강사",
    "보습학원 강사",
    "과외",
    "Private Tutor",
    "강사"
   ],
   "q": 17
  },
  {
   "id": "edu_planner",
   "family": "edu_business",
   "ko": "교육기획·교육콘텐츠",
   "en": "Education Program Planner",
   "aliases": [
    "교육기획·교육콘텐츠",
    "Education Program Planner",
    "교육기획",
    "교육콘텐츠",
    "교육 기획자",
    "교육 운영",
    "교수설계",
    "Instructional Designer",
    "이러닝 기획"
   ],
   "q": 17
  },
  {
   "id": "corporate_trainer",
   "family": "edu_business",
   "ko": "기업교육 강사",
   "en": "Corporate Trainer",
   "aliases": [
    "기업교육 강사",
    "Corporate Trainer",
    "사내강사",
    "기업 강사",
    "퍼실리테이터",
    "HRD 강사",
    "Facilitator",
    "직무교육 강사"
   ],
   "q": 17
  },
  {
   "id": "nurse",
   "family": "nursing",
   "ko": "간호사",
   "en": "Registered Nurse",
   "aliases": [
    "간호사",
    "Registered Nurse",
    "병동 간호사",
    "임상간호사",
    "신규 간호사",
    "RN",
    "Staff Nurse",
    "대학병원 간호사",
    "간호"
   ],
   "q": 28
  },
  {
   "id": "nurse_aide",
   "family": "nursing",
   "ko": "간호조무사",
   "en": "Nursing Assistant",
   "aliases": [
    "간호조무사",
    "Nursing Assistant",
    "간호보조",
    "간조",
    "의원 간호조무사",
    "요양병원 간호조무사",
    "Nurse Aide"
   ],
   "q": 17
  },
  {
   "id": "physician",
   "family": "medical_staff",
   "ko": "의사(전공의)",
   "en": "Physician / Resident",
   "aliases": [
    "의사(전공의)",
    "Physician / Resident",
    "의사",
    "전공의",
    "레지던트",
    "인턴",
    "수련의",
    "Resident",
    "Physician",
    "Medical Doctor"
   ],
   "q": 17
  },
  {
   "id": "pharmacist",
   "family": "medical_staff",
   "ko": "약사",
   "en": "Pharmacist",
   "aliases": [
    "약사",
    "Pharmacist",
    "병원약사",
    "약제부 약사",
    "근무약사",
    "개국약사",
    "Clinical Pharmacist"
   ],
   "q": 16
  },
  {
   "id": "hospital_admin",
   "family": "medical_staff",
   "ko": "병원행정·원무",
   "en": "Hospital Administrator",
   "aliases": [
    "병원행정·원무",
    "Hospital Administrator",
    "병원행정",
    "원무",
    "원무과",
    "원무팀",
    "병원 사무직",
    "Patient Accounts"
   ],
   "q": 16
  },
  {
   "id": "medical_coordinator",
   "family": "medical_staff",
   "ko": "병원 코디네이터",
   "en": "Medical Coordinator",
   "aliases": [
    "병원 코디네이터",
    "Medical Coordinator",
    "상담실장",
    "상담 코디네이터",
    "치과 코디네이터",
    "피부과 코디",
    "Patient Coordinator"
   ],
   "q": 16
  },
  {
   "id": "physical_therapist",
   "family": "allied_health",
   "ko": "물리치료사",
   "en": "Physical Therapist",
   "aliases": [
    "물리치료사",
    "Physical Therapist",
    "PT",
    "도수치료사",
    "Physiotherapist"
   ],
   "q": 16
  },
  {
   "id": "occupational_therapist",
   "family": "allied_health",
   "ko": "작업치료사",
   "en": "Occupational Therapist",
   "aliases": [
    "작업치료사",
    "Occupational Therapist",
    "OT",
    "감각통합치료사",
    "연하재활"
   ],
   "q": 16
  },
  {
   "id": "clinical_lab_scientist",
   "family": "allied_health",
   "ko": "임상병리사",
   "en": "Clinical Laboratory Scientist",
   "aliases": [
    "임상병리사",
    "Clinical Laboratory Scientist",
    "진단검사 임상병리사",
    "검사실",
    "채혈",
    "생리기능검사",
    "Medical Technologist"
   ],
   "q": 16
  },
  {
   "id": "radiologic_technologist",
   "family": "allied_health",
   "ko": "방사선사",
   "en": "Radiologic Technologist",
   "aliases": [
    "방사선사",
    "Radiologic Technologist",
    "영상의학과 방사선사",
    "CT 방사선사",
    "MRI 방사선사",
    "Radiographer"
   ],
   "q": 17
  },
  {
   "id": "dental_hygienist",
   "family": "allied_health",
   "ko": "치과위생사",
   "en": "Dental Hygienist",
   "aliases": [
    "치과위생사",
    "Dental Hygienist",
    "치위생사",
    "덴탈 하이지니스트"
   ],
   "q": 17
  },
  {
   "id": "dietitian",
   "family": "allied_health",
   "ko": "영양사",
   "en": "Dietitian",
   "aliases": [
    "영양사",
    "Dietitian",
    "임상영양사",
    "급식 영양사",
    "학교 영양사",
    "위탁급식 영양사",
    "Clinical Dietitian"
   ],
   "q": 16
  },
  {
   "id": "public_health_officer",
   "family": "public_health",
   "ko": "보건직(보건소)",
   "en": "Public Health Officer",
   "aliases": [
    "보건직(보건소)",
    "Public Health Officer",
    "보건직",
    "보건소",
    "보건직 공무원",
    "보건행정",
    "지방보건직"
   ],
   "q": 16
  },
  {
   "id": "social_worker",
   "family": "welfare",
   "ko": "사회복지사",
   "en": "Social Worker",
   "aliases": [
    "사회복지사",
    "Social Worker",
    "사회복지 전담공무원",
    "복지관 사회복지사",
    "사례관리자"
   ],
   "q": 16
  },
  {
   "id": "care_manager",
   "family": "welfare",
   "ko": "요양·돌봄 관리",
   "en": "Care Manager",
   "aliases": [
    "요양·돌봄 관리",
    "Care Manager",
    "요양",
    "돌봄 관리",
    "요양 관리자",
    "요양원 사회복지사",
    "재가복지 관리자",
    "센터장",
    "돌봄 코디네이터"
   ],
   "q": 16
  },
  {
   "id": "youth_worker",
   "family": "welfare",
   "ko": "청소년지도사",
   "en": "Youth Worker",
   "aliases": [
    "청소년지도사",
    "Youth Worker",
    "청소년 수련관",
    "청소년 활동 지도자",
    "청소년센터"
   ],
   "q": 16
  },
  {
   "id": "medical_social_worker",
   "family": "welfare",
   "ko": "의료사회복지사",
   "en": "Medical Social Worker",
   "aliases": [
    "의료사회복지사",
    "Medical Social Worker",
    "병원 사회복지사",
    "사회사업팀",
    "정신건강사회복지사"
   ],
   "q": 16
  },
  {
   "id": "counselor",
   "family": "counseling",
   "ko": "심리상담사",
   "en": "Counselor / Psychotherapist",
   "aliases": [
    "심리상담사",
    "Counselor / Psychotherapist",
    "상담심리사",
    "전문상담사",
    "심리치료사",
    "Counselor",
    "Psychotherapist"
   ],
   "q": 16
  },
  {
   "id": "career_counselor",
   "family": "counseling",
   "ko": "진로·취업상담사",
   "en": "Career Counselor",
   "aliases": [
    "진로·취업상담사",
    "Career Counselor",
    "진로",
    "취업상담사",
    "진로상담사",
    "직업상담사",
    "커리어 컨설턴트",
    "잡매니저"
   ],
   "q": 16
  },
  {
   "id": "school_counselor",
   "family": "counseling",
   "ko": "전문상담교사",
   "en": "School Counselor",
   "aliases": [
    "전문상담교사",
    "School Counselor",
    "학교 상담교사",
    "Wee클래스",
    "학교상담"
   ],
   "q": 16
  },
  {
   "id": "hotelier",
   "family": "hotel_tourism",
   "ko": "호텔리어(프런트·객실)",
   "en": "Hotel Front Office",
   "aliases": [
    "호텔리어(프런트·객실)",
    "Hotel Front Office",
    "호텔리어",
    "객실",
    "프론트 데스크",
    "객실팀",
    "객실부",
    "Front Office",
    "Guest Service Agent",
    "호텔 객실관리",
    "컨시어지"
   ],
   "q": 18
  },
  {
   "id": "hotel_sales",
   "family": "hotel_tourism",
   "ko": "호텔 세일즈·마케팅",
   "en": "Hotel Sales",
   "aliases": [
    "호텔 세일즈·마케팅",
    "Hotel Sales",
    "호텔 세일즈",
    "호텔 영업",
    "호텔 마케팅",
    "세일즈 매니저",
    "세일즈 코디네이터",
    "객실 세일즈",
    "연회 세일즈",
    "Revenue"
   ],
   "q": 17
  },
  {
   "id": "travel_planner",
   "family": "hotel_tourism",
   "ko": "여행상품기획",
   "en": "Travel Product Planner",
   "aliases": [
    "여행상품기획",
    "Travel Product Planner",
    "여행상품개발자",
    "여행 MD",
    "투어 플래너",
    "여행사 기획",
    "패키지 기획"
   ],
   "q": 17
  },
  {
   "id": "tour_guide",
   "family": "hotel_tourism",
   "ko": "관광통역안내사",
   "en": "Tour Guide",
   "aliases": [
    "관광통역안내사",
    "Tour Guide",
    "관광통역안내원",
    "가이드",
    "통역 가이드",
    "인바운드 가이드",
    "관광 가이드"
   ],
   "q": 16
  },
  {
   "id": "mice_planner",
   "family": "hotel_tourism",
   "ko": "MICE 기획",
   "en": "MICE Planner",
   "aliases": [
    "MICE 기획",
    "MICE Planner",
    "컨벤션기획사",
    "행사기획자",
    "PCO",
    "이벤트 플래너",
    "회의기획자"
   ],
   "q": 17
  },
  {
   "id": "flight_attendant",
   "family": "aviation",
   "ko": "객실승무원",
   "en": "Flight Attendant",
   "aliases": [
    "객실승무원",
    "Flight Attendant",
    "승무원",
    "스튜어디스",
    "스튜어드",
    "캐빈크루",
    "Cabin Crew",
    "인턴 승무원"
   ],
   "q": 30
  },
  {
   "id": "ground_staff",
   "family": "aviation",
   "ko": "항공 지상직",
   "en": "Airline Ground Staff",
   "aliases": [
    "항공 지상직",
    "Airline Ground Staff",
    "지상직",
    "공항 서비스",
    "여객운송",
    "탑승수속",
    "카운터",
    "Ground Staff",
    "Passenger Service Agent",
    "공항 운송"
   ],
   "q": 18
  },
  {
   "id": "pilot",
   "family": "aviation",
   "ko": "조종사",
   "en": "Pilot",
   "aliases": [
    "조종사",
    "Pilot",
    "운항승무원",
    "기장",
    "부기장",
    "파일럿",
    "First Officer",
    "Captain",
    "항공기조종사"
   ],
   "q": 18
  },
  {
   "id": "aircraft_mechanic",
   "family": "aviation",
   "ko": "항공정비사",
   "en": "Aircraft Maintenance Technician",
   "aliases": [
    "항공정비사",
    "Aircraft Maintenance Technician",
    "항공기정비원",
    "정비사",
    "라인정비",
    "운항정비",
    "기체정비",
    "Aircraft Mechanic",
    "AMT",
    "MRO"
   ],
   "q": 18
  },
  {
   "id": "restaurant_manager",
   "family": "food_service",
   "ko": "외식 매장관리",
   "en": "Restaurant Manager",
   "aliases": [
    "외식 매장관리",
    "Restaurant Manager",
    "홀 매니저",
    "외식 점포관리",
    "Store Manager(F&B)"
   ],
   "q": 17
  },
  {
   "id": "chef",
   "family": "food_service",
   "ko": "조리사·셰프",
   "en": "Chef / Cook",
   "aliases": [
    "조리사·셰프",
    "Chef / Cook",
    "조리사",
    "셰프",
    "요리사",
    "주방",
    "Chef",
    "Cook",
    "조리 담당"
   ],
   "q": 17
  },
  {
   "id": "barista",
   "family": "food_service",
   "ko": "바리스타",
   "en": "Barista",
   "aliases": [
    "바리스타",
    "Barista",
    "카페 직원",
    "커피 전문가",
    "카페 매니저"
   ],
   "q": 16
  },
  {
   "id": "food_researcher",
   "family": "food_industry",
   "ko": "식품 연구개발",
   "en": "Food R&D Researcher",
   "aliases": [
    "식품 연구개발",
    "Food R&D Researcher",
    "식품 R&D",
    "식품연구원",
    "식품개발",
    "Food R&D",
    "Food Scientist",
    "식품공학"
   ],
   "q": 17
  },
  {
   "id": "food_quality",
   "family": "food_industry",
   "ko": "식품 품질·위생(HACCP)",
   "en": "Food Quality & Safety",
   "aliases": [
    "식품 품질·위생(HACCP)",
    "Food Quality & Safety",
    "식품 품질·위생",
    "HACCP",
    "식품 품질",
    "위생",
    "식품 품질관리",
    "식품 QA",
    "식품 QC",
    "HACCP 담당",
    "위생관리",
    "Food Safety"
   ],
   "q": 17
  },
  {
   "id": "store_manager",
   "family": "retail",
   "ko": "매장관리·점장",
   "en": "Store Manager",
   "aliases": [
    "매장관리·점장",
    "Store Manager",
    "매장관리",
    "점포 운영",
    "스토어 매니저",
    "매장 운영관리"
   ],
   "q": 18
  },
  {
   "id": "retail_sm",
   "family": "retail",
   "ko": "유통 영업관리(SM)",
   "en": "Retail Sales Manager",
   "aliases": [
    "유통 영업관리(SM)",
    "Retail Sales Manager",
    "유통 영업관리",
    "SM",
    "스토어 매니저(유통사)",
    "OFC",
    "SC",
    "점포 영업관리",
    "백화점 영업관리"
   ],
   "q": 19
  },
  {
   "id": "ecommerce_ops",
   "family": "retail",
   "ko": "이커머스 운영",
   "en": "E-commerce Operations",
   "aliases": [
    "이커머스 운영",
    "E-commerce Operations",
    "온라인몰 운영",
    "쇼핑몰 운영",
    "커머스 운영",
    "온라인 MD 운영",
    "마켓플레이스 운영"
   ],
   "q": 17
  },
  {
   "id": "vmd",
   "family": "retail",
   "ko": "VMD",
   "en": "Visual Merchandiser",
   "aliases": [
    "VMD",
    "Visual Merchandiser",
    "비주얼 머천다이저",
    "비주얼 머천다이징",
    "매장 연출",
    "디스플레이어",
    "VM"
   ],
   "q": 17
  },
  {
   "id": "admin_civil_servant",
   "family": "civil_service",
   "ko": "일반행정 공무원",
   "en": "Administrative Civil Servant",
   "aliases": [
    "일반행정 공무원",
    "Administrative Civil Servant",
    "일반행정직",
    "행정직 공무원",
    "9급 일반행정",
    "7급 행정직",
    "지방행정직",
    "주민센터 공무원",
    "Administrative Officer",
    "행정주사보",
    "공무원",
    "9급 공무원",
    "7급 공무원"
   ],
   "q": 30
  },
  {
   "id": "tech_civil_servant",
   "family": "civil_service",
   "ko": "기술직 공무원",
   "en": "Technical Civil Servant",
   "aliases": [
    "기술직 공무원",
    "Technical Civil Servant",
    "시설직",
    "토목직 공무원",
    "건축직 공무원",
    "전기직 공무원",
    "공업직",
    "Technical Officer"
   ],
   "q": 20
  },
  {
   "id": "tax_official",
   "family": "civil_service",
   "ko": "세무직 공무원",
   "en": "Tax Official",
   "aliases": [
    "세무직 공무원",
    "Tax Official",
    "세무직",
    "세무공무원",
    "국세공무원",
    "지방세 공무원",
    "세무서 직원",
    "Tax Officer"
   ],
   "q": 20
  },
  {
   "id": "police_officer",
   "family": "civil_service",
   "ko": "경찰",
   "en": "Police Officer",
   "aliases": [
    "경찰",
    "Police Officer",
    "경찰관",
    "순경",
    "경찰공무원",
    "지구대 경찰",
    "경찰 간부후보"
   ],
   "q": 17
  },
  {
   "id": "firefighter",
   "family": "civil_service",
   "ko": "소방관",
   "en": "Firefighter",
   "aliases": [
    "소방관",
    "Firefighter",
    "소방공무원",
    "소방사",
    "119 구조대원",
    "구급대원",
    "화재진압대원"
   ],
   "q": 18
  },
  {
   "id": "military_officer",
   "family": "civil_service",
   "ko": "군 간부",
   "en": "Military Officer",
   "aliases": [
    "군 간부",
    "Military Officer",
    "장교",
    "부사관",
    "소대장",
    "ROTC",
    "학사장교",
    "NCO"
   ],
   "q": 17
  },
  {
   "id": "pe_admin",
   "family": "public_enterprise",
   "ko": "공기업 사무·행정",
   "en": "Public Enterprise Administration",
   "aliases": [
    "공기업 사무·행정",
    "Public Enterprise Administration",
    "공기업 사무",
    "공기업 사무직",
    "공기업 행정직",
    "공공기관 사무직",
    "공기업 경영지원",
    "사무 일반",
    "NCS 사무행정"
   ],
   "q": 27
  },
  {
   "id": "pe_electrical",
   "family": "public_enterprise",
   "ko": "공기업 전기직",
   "en": "Public Enterprise Electrical Engineer",
   "aliases": [
    "공기업 전기직",
    "Public Enterprise Electrical Engineer",
    "전기 직렬",
    "발전소 전기직",
    "Power Utility Electrical Engineer"
   ],
   "q": 20
  },
  {
   "id": "pe_mechanical",
   "family": "public_enterprise",
   "ko": "공기업 기계직",
   "en": "Public Enterprise Mechanical Engineer",
   "aliases": [
    "공기업 기계직",
    "Public Enterprise Mechanical Engineer",
    "발전소 기계직",
    "플랜트 정비",
    "기계 직렬",
    "Power Plant Mechanical Engineer"
   ],
   "q": 18
  },
  {
   "id": "pe_civil",
   "family": "public_enterprise",
   "ko": "공기업 토목직",
   "en": "Public Enterprise Civil Engineer",
   "aliases": [
    "공기업 토목직",
    "Public Enterprise Civil Engineer",
    "토목 직렬",
    "공사 감독",
    "도로·철도 토목",
    "시설 유지관리"
   ],
   "q": 19
  },
  {
   "id": "pe_it",
   "family": "public_enterprise",
   "ko": "공기업 전산직",
   "en": "Public Enterprise IT",
   "aliases": [
    "공기업 전산직",
    "Public Enterprise IT",
    "ICT 직렬",
    "공공기관 IT",
    "정보화 담당",
    "정보보안 담당"
   ],
   "q": 16
  },
  {
   "id": "ngo_program",
   "family": "nonprofit",
   "ko": "비영리 사업·프로그램 매니저",
   "en": "NGO Program Manager",
   "aliases": [
    "비영리 사업·프로그램 매니저",
    "NGO Program Manager",
    "비영리 사업",
    "프로그램 매니저",
    "NGO 사업 담당",
    "비영리 프로그램 매니저",
    "국제개발협력 PM",
    "복지사업 담당",
    "사업팀",
    "Program Manager"
   ],
   "q": 17
  },
  {
   "id": "fundraiser",
   "family": "nonprofit",
   "ko": "모금·후원 담당",
   "en": "Fundraiser",
   "aliases": [
    "모금·후원 담당",
    "Fundraiser",
    "모금",
    "후원 담당",
    "모금·후원",
    "모금 담당",
    "후원자 관리",
    "펀드레이저",
    "대외협력",
    "Donor Relations"
   ],
   "q": 16
  },
  {
   "id": "public_institution_staff",
   "family": "nonprofit",
   "ko": "공공기관 행정직",
   "en": "Public Institution Staff",
   "aliases": [
    "공공기관 행정직",
    "Public Institution Staff",
    "준정부기관 직원",
    "기타공공기관 행정",
    "진흥원 행정",
    "재단 행정직"
   ],
   "q": 16
  },
  {
   "id": "policy_researcher",
   "family": "research_institute",
   "ko": "정책 연구원",
   "en": "Policy Researcher",
   "aliases": [
    "정책 연구원",
    "Policy Researcher",
    "국책연구기관 연구원",
    "연구위원",
    "부연구위원",
    "싱크탱크 연구원"
   ],
   "q": 17
  },
  {
   "id": "gov_researcher",
   "family": "research_institute",
   "ko": "출연연 연구원",
   "en": "Government-funded Institute Researcher",
   "aliases": [
    "출연연 연구원",
    "Government-funded Institute Researcher",
    "정부출연연구기관 연구직",
    "국가연구소 연구원",
    "Government Research Institute Researcher"
   ],
   "q": 16
  },
  {
   "id": "research_admin",
   "family": "research_institute",
   "ko": "연구행정",
   "en": "Research Administrator",
   "aliases": [
    "연구행정",
    "Research Administrator",
    "과제 행정",
    "연구원 행정직"
   ],
   "q": 16
  },
  {
   "id": "curator",
   "family": "culture_arts",
   "ko": "큐레이터·학예사",
   "en": "Curator",
   "aliases": [
    "큐레이터·학예사",
    "Curator",
    "큐레이터",
    "학예사",
    "학예연구사",
    "학예연구관"
   ],
   "q": 18
  },
  {
   "id": "performance_planner",
   "family": "culture_arts",
   "ko": "공연·전시기획",
   "en": "Performing Arts Producer",
   "aliases": [
    "공연·전시기획",
    "Performing Arts Producer",
    "공연",
    "공연기획자",
    "공연 PD",
    "문화행사 기획"
   ],
   "q": 16
  },
  {
   "id": "arts_educator",
   "family": "culture_arts",
   "ko": "문화예술교육사",
   "en": "Arts Educator",
   "aliases": [
    "문화예술교육사",
    "Arts Educator",
    "예술교육 기획자",
    "예술강사",
    "문화예술교육 담당",
    "교육 코디네이터"
   ],
   "q": 16
  },
  {
   "id": "sports_marketer",
   "family": "sports",
   "ko": "스포츠 마케팅",
   "en": "Sports Marketer",
   "aliases": [
    "스포츠 마케팅",
    "Sports Marketer",
    "스포츠 마케터",
    "구단 마케팅",
    "스포츠 마케팅 매니저",
    "스폰서십 담당"
   ],
   "q": 16
  },
  {
   "id": "fitness_trainer",
   "family": "sports",
   "ko": "운동처방·트레이너",
   "en": "Fitness Trainer",
   "aliases": [
    "운동처방·트레이너",
    "Fitness Trainer",
    "운동처방",
    "트레이너",
    "퍼스널 트레이너",
    "PT 트레이너",
    "운동처방사",
    "건강운동관리사",
    "재활 트레이너"
   ],
   "q": 16
  },
  {
   "id": "sports_admin",
   "family": "sports",
   "ko": "스포츠 행정·구단 운영",
   "en": "Sports Administrator",
   "aliases": [
    "스포츠 행정·구단 운영",
    "Sports Administrator",
    "스포츠 행정",
    "구단 운영",
    "체육단체 행정",
    "대회 운영"
   ],
   "q": 17
  },
  {
   "id": "labor_attorney",
   "family": "licensed",
   "ko": "공인노무사",
   "en": "Certified Labor Attorney",
   "aliases": [
    "공인노무사",
    "Certified Labor Attorney",
    "노무사",
    "수습 노무사",
    "노무법인 노무사",
    "Labor Attorney",
    "Certified Public Labor Attorney"
   ],
   "q": 17
  },
  {
   "id": "customs_broker",
   "family": "licensed",
   "ko": "관세사",
   "en": "Customs Broker",
   "aliases": [
    "관세사",
    "Customs Broker",
    "관세법인 관세사",
    "통관 전문가",
    "Licensed Customs Broker",
    "Customs Specialist"
   ],
   "q": 17
  },
  {
   "id": "patent_attorney",
   "family": "licensed",
   "ko": "변리사",
   "en": "Patent Attorney",
   "aliases": [
    "변리사",
    "Patent Attorney",
    "특허 변리사",
    "특허법인 변리사",
    "수습 변리사",
    "Patent Agent"
   ],
   "q": 16
  },
  {
   "id": "appraiser",
   "family": "licensed",
   "ko": "감정평가사",
   "en": "Certified Appraiser",
   "aliases": [
    "감정평가사",
    "Certified Appraiser",
    "감정평가법인 감정평가사",
    "수습 감정평가사",
    "Real Estate Appraiser",
    "Appraiser"
   ],
   "q": 16
  },
  {
   "id": "translator",
   "family": "language_realestate",
   "ko": "통번역사",
   "en": "Translator / Interpreter",
   "aliases": [
    "통번역사",
    "Translator / Interpreter",
    "통역사",
    "번역가",
    "번역사",
    "사내 통번역사",
    "인하우스 통번역사",
    "Translator",
    "Interpreter"
   ],
   "q": 17
  },
  {
   "id": "real_estate_manager",
   "family": "language_realestate",
   "ko": "부동산 자산관리",
   "en": "Real Estate Asset Manager",
   "aliases": [
    "부동산 자산관리",
    "Real Estate Asset Manager",
    "부동산 자산관리 담당자",
    "부동산 PM",
    "프로퍼티 매니저",
    "빌딩 매니저",
    "Property Manager",
    "Property Management Specialist"
   ],
   "q": 16
  }
 ],
 "stats": {
  "roles": 256,
  "domains": 51,
  "families": 72,
  "questions": 6819,
  "commonQuestions": 383,
  "byBasis": {
   "공개후기": 268,
   "공식자료": 452,
   "공고기반": 11,
   "직무기반": 5761,
   "일반면접": 327
  },
  "sources": 152,
  "generatedAt": "2026-09-30"
 }
};
