import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { lazy, Suspense, useState } from "react";
import { InterviewHistory } from "../components/InterviewHistory";
const ScoreTrend = lazy(() => import("../components/ScoreTrend").then((m) => ({ default: m.ScoreTrend })));
import { TopBar } from "../components/TopBar";
import { Button } from "../components/ui/Button";
import { Dialog } from "../components/ui/Dialog";
export function HistoryPage({ history, onOpen, canOpen, onStart, onHome, onClear }) {
    const [confirm, setConfirm] = useState(false);
    const avg = history.length ? Math.round(history.reduce((s, h) => s + h.score, 0) / history.length) : null;
    const best = history.length ? Math.max(...history.map((h) => h.score)) : null;
    return (_jsxs("div", { className: "min-h-dvh pb-16", children: [_jsx(TopBar, { onHome: onHome, right: _jsx(Button, { size: "sm", variant: "primary", onClick: onStart, children: "\uC0C8 \uBA74\uC811 \uBCF4\uAE30" }) }), _jsxs("main", { className: "mx-auto w-full max-w-3xl px-4 sm:px-6", children: [_jsxs("div", { className: "flex flex-wrap items-end justify-between gap-4 pt-8 pb-6", children: [_jsxs("div", { children: [_jsx("p", { className: "text-sm font-semibold text-accent", children: "\uB098\uC758 \uBA74\uC811 \uAE30\uB85D" }), _jsx("h1", { className: "mt-1.5 text-2xl font-extrabold text-navy", children: "\uC751\uC2DC\uD55C \uBAA8\uC758\uBA74\uC811" })] }), avg !== null && (_jsxs("dl", { className: "flex gap-6 text-[13px] text-muted", children: [_jsxs("div", { children: [_jsx("dd", { className: "font-mono text-xl font-semibold text-ink", children: history.length }), _jsx("dt", { children: "\uC751\uC2DC \uD69F\uC218" })] }), _jsxs("div", { children: [_jsx("dd", { className: "font-mono text-xl font-semibold text-ink", children: avg }), _jsx("dt", { children: "\uD3C9\uADE0 \uC810\uC218" })] }), _jsxs("div", { children: [_jsx("dd", { className: "font-mono text-xl font-semibold text-ink", children: best }), _jsx("dt", { children: "\uCD5C\uACE0 \uC810\uC218" })] })] }))] }), history.length >= 2 && (_jsx("div", { className: "mb-5", children: _jsx(Suspense, { fallback: _jsx("div", { className: "h-[250px] rounded-xl border border-line bg-surface" }), children: _jsx(ScoreTrend, { history: history }) }) })), _jsx(InterviewHistory, { items: history, onOpen: onOpen, onStart: onStart, canOpen: canOpen }), history.length > 0 && (_jsxs("div", { className: "mt-5 flex items-center justify-between gap-4 text-[12px] text-faint", children: [_jsx("span", { children: "\uAE30\uB85D\uC740 \uC774 \uBE0C\uB77C\uC6B0\uC800(localStorage)\uC5D0\uB9CC \uC800\uC7A5\uB429\uB2C8\uB2E4. \uCD5C\uADFC 10\uD68C\uB294 \uD3C9\uAC00\uD45C \uC804\uCCB4\uAC00 \uBCF4\uAD00\uB429\uB2C8\uB2E4." }), _jsx(Button, { size: "sm", variant: "ghost", onClick: () => setConfirm(true), children: "\uAE30\uB85D \uC0AD\uC81C" })] }))] }), _jsx(Dialog, { open: confirm, title: "\uBAA8\uB4E0 \uAE30\uB85D\uC744 \uC0AD\uC81C\uD560\uAE4C\uC694?", onClose: () => setConfirm(false), actions: _jsxs(_Fragment, { children: [_jsx(Button, { size: "sm", variant: "ghost", onClick: () => setConfirm(false), children: "\uCDE8\uC18C" }), _jsx(Button, { size: "sm", variant: "danger", onClick: () => {
                                onClear();
                                setConfirm(false);
                            }, children: "\uC804\uCCB4 \uC0AD\uC81C" })] }), children: "\uC774 \uBE0C\uB77C\uC6B0\uC800\uC5D0 \uC800\uC7A5\uB41C \uBAA8\uB4E0 \uBA74\uC811 \uAE30\uB85D\uACFC \uC124\uC815\uC774 \uC0AD\uC81C\uB418\uBA70, \uB418\uB3CC\uB9B4 \uC218 \uC5C6\uC2B5\uB2C8\uB2E4." })] }));
}
