/** Interview-area copy. The app chrome is Korean; these follow the interview language. */
export const COPY = {
    ko: {
        lang: "ko",
        placeholder: "답변을 입력하거나, [음성 답변]을 눌러 말로 답해 주세요. 결론부터 말하면 좋아요.",
        placeholderWaiting: "면접관의 다음 질문을 기다리는 중입니다…",
        timeAlmostUp: "답변 시간이 얼마 남지 않았습니다. 마무리해 주세요.",
        timeUp: "답변 시간이 지났습니다. 정리해서 제출해 주세요.",
        emptyAnswer: "답변을 입력하면 제출할 수 있어요. (Ctrl/⌘ + Enter)",
        textMode: "이 브라우저는 음성 답변을 지원하지 않아 텍스트로 진행합니다.",
        recording: "말씀을 받아 적고 있어요… 끝나면 [정지]를 눌러 주세요.",
        yourAnswer: "방금 제 답변",
        pickingUp: "답변에서 짚은 부분",
        followUp: "꼬리질문",
        nextQuestion: "다음 질문",
        stages: ["답변 제출", "면접관 검토", "평가 기록"],
        whyFollowUp: "질문 의도",
        repeat: "질문 다시 듣기",
        dontKnow: "잘 모르겠어요",
        dontKnowAnswer: "죄송합니다. 그 부분은 잘 모르겠습니다.",
    },
    en: {
        lang: "en",
        placeholder: "Type your answer, or press [음성 답변] and speak. Lead with your conclusion.",
        placeholderWaiting: "Listening to the interviewer…",
        timeAlmostUp: "Time is almost up — start wrapping up.",
        timeUp: "Time's up. Wrap up and submit when ready.",
        emptyAnswer: "Write an answer to submit. (Ctrl/⌘ + Enter)",
        textMode: "Voice input isn't supported in this browser — using text mode.",
        recording: "Transcribing… press [정지] when you're done.",
        yourAnswer: "My answer",
        pickingUp: "Picking up on",
        followUp: "Follow-up",
        nextQuestion: "Next question",
        stages: ["Submitted", "Panel reviewing", "Scoring"],
        whyFollowUp: "Intent",
        repeat: "Hear it again",
        dontKnow: "I don't know",
        dontKnowAnswer: "I'm sorry, I don't know the answer to that.",
    },
};
