import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion } from "framer-motion";
import { buildPanel } from "../config/panel";
import { durationLabel } from "../utils/format";
import { InterviewRoom } from "./InterviewRoom";
import { getCompany } from "../../shared/companies";
export function CompletionScreen({ interview }) {
    const answered = interview.questions.length;
    return (_jsxs("div", { className: "fixed inset-0 z-40 flex flex-col bg-bg", role: "status", "aria-live": "polite", children: [_jsx("div", { className: "w-full border-b border-line bg-[#dfe3e8]", children: _jsx("div", { className: "mx-auto aspect-[1200/520] h-[36vh] max-h-[420px] min-h-[170px] max-w-full overflow-hidden opacity-95", children: _jsx(InterviewRoom, { panel: buildPanel(interview.config.position), speaking: null, mode: "reviewing", companyName: getCompany(interview.config.companyId)?.shortName ?? getCompany(interview.config.companyId)?.name }) }) }), _jsx("div", { className: "flex flex-1 items-center justify-center px-6", children: _jsxs("div", { className: "text-center", children: [_jsx(motion.p, { className: "text-sm font-semibold text-accent", initial: { opacity: 0 }, animate: { opacity: 1 }, children: interview.endedEarly ? "면접이 조기 종료되었습니다" : "모든 질문에 답변하셨습니다" }), _jsx(motion.h1, { className: "mt-3 text-3xl font-bold text-ink sm:text-4xl", initial: { opacity: 0, y: 8 }, animate: { opacity: 1, y: 0 }, transition: { duration: 0.5 }, children: "\uBA74\uC811\uC774 \uC885\uB8CC\uB418\uC5C8\uC2B5\uB2C8\uB2E4" }), _jsx(motion.p, { className: "mt-2 text-muted", initial: { opacity: 0 }, animate: { opacity: 1 }, transition: { delay: 0.3 }, children: "\uC218\uACE0 \uB9CE\uC73C\uC168\uC2B5\uB2C8\uB2E4. \uC548\uB155\uD788 \uAC00\uC138\uC694." }), _jsxs(motion.div, { className: "mt-6 flex justify-center gap-10", initial: { opacity: 0 }, animate: { opacity: 1 }, transition: { delay: 0.5 }, children: [_jsxs("span", { className: "text-sm text-muted", children: [_jsx("span", { className: "block font-mono text-2xl font-semibold text-ink tabular-nums", children: answered }), "\uB2F5\uBCC0 \uBB38\uD56D"] }), _jsxs("span", { className: "text-sm text-muted", children: [_jsx("span", { className: "block font-mono text-2xl font-semibold text-ink tabular-nums", children: durationLabel(interview.duration) }), "\uC18C\uC694 \uC2DC\uAC04"] })] }), _jsxs(motion.div, { className: "mx-auto mt-8 w-64", initial: { opacity: 0 }, animate: { opacity: 1 }, transition: { delay: 0.8 }, children: [_jsx("p", { className: "mb-2.5 text-sm text-muted", children: "\uBA74\uC811\uC704\uC6D0\uC774 \uD3C9\uAC00\uD45C\uB97C \uC791\uC131\uD558\uACE0 \uC788\uC2B5\uB2C8\uB2E4\u2026" }), _jsx("div", { className: "h-1 overflow-hidden rounded bg-surface-3", children: _jsx(motion.div, { className: "h-full w-1/3 bg-accent", animate: { x: ["-100%", "300%"] }, transition: { duration: 1.2, repeat: Infinity, ease: "easeInOut" } }) })] })] }) })] }));
}
