import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { AnimatePresence, motion } from "framer-motion";
import { pad2 } from "../utils/format";
import { scoreTone } from "../utils/scoring";
import { ScoreBadge } from "./ScoreBadge";
/** Running transcript of the interview — shows how each follow-up came from an answer. */
export function InterviewNotes({ questions, liveFeedback, copy }) {
    return (_jsxs("div", { className: "flex h-full flex-col", children: [_jsxs("div", { className: "flex items-center justify-between border-b border-line px-5 py-4", children: [_jsx("h2", { className: "text-sm font-bold text-ink", children: "\uBA74\uC811 \uAE30\uB85D" }), _jsxs("span", { className: "text-[12px] text-faint", children: ["\uB2F5\uBCC0 ", questions.filter((q) => q.answer).length, "\uAC1C"] })] }), _jsxs("ol", { lang: copy.lang, className: "scroll-thin flex-1 space-y-1 overflow-y-auto px-3 py-3", children: [questions.length === 0 && _jsx("li", { className: "px-2 py-6 text-center text-sm text-faint", children: "\uBA74\uC811\uC774 \uC9C4\uD589\uB418\uBA74 \uC9C8\uBB38\uACFC \uB2F5\uBCC0\uC774 \uC5EC\uAE30\uC5D0 \uAE30\uB85D\uB429\uB2C8\uB2E4." }), _jsx(AnimatePresence, { initial: false, children: questions.map((q, i) => (_jsxs(motion.li, { initial: { opacity: 0, x: 8 }, animate: { opacity: 1, x: 0 }, className: `rounded-lg px-3 py-3 ${q.isFollowUp ? "ml-4 border-l-2 border-accent/30" : ""} ${!q.answer ? "bg-accent-soft" : ""}`, children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsxs("span", { className: "font-mono text-[11px] font-semibold text-faint", children: ["Q", pad2(i + 1)] }), q.isFollowUp && _jsxs("span", { className: "text-[11px] font-semibold text-accent", children: ["\u21B3 ", copy.followUp] }), liveFeedback && q.score !== null && (_jsx("span", { className: "ml-auto", children: _jsx(ScoreBadge, { score: q.score, tone: scoreTone(q.score), small: true }) }))] }), _jsx("p", { className: "mt-1.5 text-[13px] leading-snug font-medium text-ink", children: q.text }), q.isFollowUp && q.followUpReason && (_jsxs("p", { className: "mt-1.5 text-[11px] leading-snug text-faint", children: [_jsxs("span", { className: "text-accent", children: [copy.whyFollowUp, ":"] }), " ", q.followUpReason] })), q.answer && _jsx("p", { className: "mt-2 line-clamp-2 border-l-2 border-line-strong pl-2 text-[12px] leading-snug text-muted", children: q.answer }), liveFeedback && q.feedback && (_jsxs("p", { className: "mt-1.5 text-[11px] leading-snug text-good", children: ["+ ", q.feedback.strength] }))] }, q.id))) })] })] }));
}
